"""Create sub_industry table

Revision ID: 29fe5590b148
Revises: f8a23e2ca419
Create Date: 2020-11-11 23:01:01.740205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fe5590b148'
down_revision = 'f8a23e2ca419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_industry',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('industry_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], name=op.f('fk_sub_industry_industry_id_industry'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_industry')),
    sa.UniqueConstraint('name', name=op.f('uq_sub_industry_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_industry')
    # ### end Alembic commands ###
