"""Add locked column to bar_data table

Revision ID: bcc76ce93a8e
Revises: cc1b5cfc3419
Create Date: 2020-12-24 14:40:18.489923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc76ce93a8e'
down_revision = 'cc1b5cfc3419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bar_data', sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bar_data', 'locked')
    # ### end Alembic commands ###
