"""name_code industry table

Revision ID: f3ec71fe86e6
Revises: e8518960f8d2
Create Date: 2020-11-22 20:53:39.363670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ec71fe86e6'
down_revision = 'e8518960f8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry', sa.Column('name_code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(op.f('uq_industry_name_code'), 'industry', ['name_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_industry_name_code'), 'industry', type_='unique')
    op.drop_column('industry', 'name_code')
    # ### end Alembic commands ###
