"""Create industry table and add nullabre flase to existing fkeys

Revision ID: f8a23e2ca419
Revises: b243e3285a26
Create Date: 2020-11-11 22:54:06.182686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a23e2ca419'
down_revision = 'b243e3285a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('sector_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], name=op.f('fk_industry_sector_id_sector'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry'))
    )
    op.alter_column('exchange', 'country_info_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange', 'country_info_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_table('industry')
    # ### end Alembic commands ###
