"""add stamp

Revision ID: c532c87952fd
Revises: 7a1fc5938c84
Create Date: 2020-12-06 16:36:55.720138

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *


# revision identifiers, used by Alembic.
revision = 'c532c87952fd'
down_revision = '7a1fc5938c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheet_data', sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False))
    op.add_column('cash_flow_statement_data', sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False))
    op.add_column('income_statement_data', sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_statement_data', 'update_stamp')
    op.drop_column('cash_flow_statement_data', 'update_stamp')
    op.drop_column('balance_sheet_data', 'update_stamp')
    # ### end Alembic commands ###
