"""Remove usd conversion cols from inc statement

Revision ID: e146d22ba811
Revises: e178ad4e1bf9
Create Date: 2020-12-06 21:15:38.401459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e146d22ba811'
down_revision = 'e178ad4e1bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_statement_data', 'ebitusd')
    op.drop_column('income_statement_data', 'revenueusd')
    op.drop_column('income_statement_data', 'netinccmnusd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_statement_data', sa.Column('netinccmnusd', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('income_statement_data', sa.Column('revenueusd', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('income_statement_data', sa.Column('ebitusd', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
