"""name_code country table

Revision ID: feb54d11c85f
Revises: 72d402e6e88f
Create Date: 2020-11-22 20:30:02.069237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb54d11c85f'
down_revision = '72d402e6e88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_info', sa.Column('name_code', sa.String(length=10), nullable=True))
    op.create_unique_constraint(op.f('uq_country_info_name_code'), 'country_info', ['name_code'])
    op.drop_constraint('uq_country_info_name_info', 'country_info', type_='unique')
    op.drop_column('country_info', 'name_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_info', sa.Column('name_info', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_country_info_name_info', 'country_info', ['name_info'])
    op.drop_constraint(op.f('uq_country_info_name_code'), 'country_info', type_='unique')
    op.drop_column('country_info', 'name_code')
    # ### end Alembic commands ###
