"""Regenerate db

Revision ID: 77fb7348217c
Revises: 2e6464807da5
Create Date: 2020-11-11 22:13:17.479633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fb7348217c'
down_revision = '2e6464807da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('name', name=op.f('uq_company_name')),
    sa.UniqueConstraint('ticker', name=op.f('uq_company_ticker'))
    )
    op.create_index(op.f('ix_company_locked'), 'company', ['locked'], unique=False)
    op.create_table('country_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_info')),
    sa.UniqueConstraint('name', name=op.f('uq_country_info_name'))
    )
    op.create_table('exchange',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('country_info_id', sa.Integer(), nullable=True),
    sa.Column('name_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['country_info_id'], ['country_info.id'], name=op.f('fk_exchange_country_info_id_country_info'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange')),
    sa.UniqueConstraint('name', name=op.f('uq_exchange_name')),
    sa.UniqueConstraint('name_code', name=op.f('uq_exchange_name_code'))
    )
    op.create_table('company_exchange_relation',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_exchange_relation_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name=op.f('fk_company_exchange_relation_exchange_id_exchange'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'exchange_id', name=op.f('pk_company_exchange_relation'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_exchange_relation')
    op.drop_table('exchange')
    op.drop_table('country_info')
    op.drop_index(op.f('ix_company_locked'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
