"""Add unique constraint to industry name

Revision ID: 51bbe3885170
Revises: 29fe5590b148
Create Date: 2020-11-11 23:02:06.447708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bbe3885170'
down_revision = '29fe5590b148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_industry_name'), 'industry', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_industry_name'), 'industry', type_='unique')
    # ### end Alembic commands ###
