"""change 2 cash flow col names

Revision ID: 330de9b51b50
Revises: e146d22ba811
Create Date: 2020-12-12 12:09:30.151207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330de9b51b50'
down_revision = 'e146d22ba811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_flow_statement_data', 'ncfiny')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flow_statement_data', sa.Column('ncfiny', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
