"""rename cols

Revision ID: 715685a4f9cf
Revises: 89a09322de51
Create Date: 2020-12-13 15:55:42.390421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '715685a4f9cf'
down_revision = '89a09322de51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheet_data', sa.Column('date_filed', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('balance_sheet_data', 'period_end_date')
    op.add_column('cash_flow_statement_data', sa.Column('date_filed', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('cash_flow_statement_data', 'period_end_date')
    op.add_column('income_statement_data', sa.Column('date_filed', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('income_statement_data', 'period_end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_statement_data', sa.Column('period_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('income_statement_data', 'date_filed')
    op.add_column('cash_flow_statement_data', sa.Column('period_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('cash_flow_statement_data', 'date_filed')
    op.add_column('balance_sheet_data', sa.Column('period_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('balance_sheet_data', 'date_filed')
    # ### end Alembic commands ###
