"""Remove sub_industry table and add company_sector_relation

Revision ID: d80ba31f7a33
Revises: b78b42e16692
Create Date: 2020-11-29 13:34:24.029697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import *

# revision identifiers, used by Alembic.
revision = 'd80ba31f7a33'
down_revision = 'b78b42e16692'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()

    op.create_table('company_sector_relation',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.SmallInteger(), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_sector_relation_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], name=op.f('fk_company_sector_relation_sector_id_sector'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'sector_id', name=op.f('pk_company_sector_relation'))
    )
    op.drop_table('sub_industry')
    op.drop_constraint('fk_company_sector_id_sector', 'company', type_='foreignkey')
    op.drop_column('company', 'sector_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('sector_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_company_sector_id_sector', 'company', 'sector', ['sector_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('sub_industry',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('sub_industry_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], name='fk_sub_industry_industry_id_industry', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_sub_industry'),
    sa.UniqueConstraint('name', name='uq_sub_industry_name')
    )
    op.drop_table('company_sector_relation')
    # ### end Alembic commands ###
