"""Add bar_data table

Revision ID: cc1b5cfc3419
Revises: 715685a4f9cf
Create Date: 2020-12-22 15:50:02.036988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1b5cfc3419'
down_revision = '715685a4f9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.SmallInteger(), nullable=False),
    sa.Column('bar_type', sa.Integer(), nullable=False),
    sa.Column('bar_open', sa.Numeric(), nullable=False),
    sa.Column('bar_high', sa.Numeric(), nullable=False),
    sa.Column('bar_low', sa.Numeric(), nullable=False),
    sa.Column('bar_close', sa.Numeric(), nullable=False),
    sa.Column('bar_volume', sa.Numeric(), nullable=True),
    sa.Column('bar_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bar_size', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_bar_data_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name=op.f('fk_bar_data_exchange_id_exchange'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bar_data')),
    sa.UniqueConstraint('company_id', 'bar_type', 'bar_size', 'bar_date', name=op.f('uq_bar_data_company_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bar_data')
    # ### end Alembic commands ###
