"""Create state_info table

Revision ID: b12948034865
Revises: 51bbe3885170
Create Date: 2020-11-14 12:12:52.703040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12948034865'
down_revision = '51bbe3885170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_info_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['country_info_id'], ['country_info.id'], name=op.f('fk_state_info_country_info_id_country_info'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_info')),
    sa.UniqueConstraint('name', name=op.f('uq_state_info_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_info')
    # ### end Alembic commands ###
