"""Remove shareswa/dil from company table

Revision ID: e178ad4e1bf9
Revises: e7ccdd1e57fd
Create Date: 2020-12-06 21:02:52.099998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e178ad4e1bf9'
down_revision = 'e7ccdd1e57fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'shares_wa')
    op.drop_column('company', 'shares_wa_dil')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('shares_wa_dil', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('shares_wa', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
