"""Add sector_id fk to company table

Revision ID: 4d14165a91a1
Revises: c8964d1978d9
Create Date: 2020-11-15 22:55:38.757025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d14165a91a1'
down_revision = 'c8964d1978d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('sector_id', sa.SmallInteger(), nullable=False))
    op.create_foreign_key(op.f('fk_company_sector_id_sector'), 'company', 'sector', ['sector_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_company_sector_id_sector'), 'company', type_='foreignkey')
    op.drop_column('company', 'sector_id')
    # ### end Alembic commands ###
