"""Add company delisted col

Revision ID: 8f8bb0fb5a5e
Revises: 4d14165a91a1
Create Date: 2020-11-19 21:37:12.544959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8bb0fb5a5e'
down_revision = '4d14165a91a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('delisted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_company_delisted'), 'company', ['delisted'], unique=False)
    op.drop_index('ix_company_locked', table_name='company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_company_locked', 'company', ['locked'], unique=False)
    op.drop_index(op.f('ix_company_delisted'), table_name='company')
    op.drop_column('company', 'delisted')
    # ### end Alembic commands ###
