"""name_code country table

Revision ID: e8518960f8d2
Revises: feb54d11c85f
Create Date: 2020-11-22 20:32:25.090045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm, SmallInteger, String, DateTime
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *


# revision identifiers, used by Alembic.
revision = 'e8518960f8d2'
down_revision = 'feb54d11c85f'
branch_labels = None
depends_on = None

meta = MetaData(naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s"
      })

Base = declarative_base(metadata=meta)

class CountryInfo(Base):
    __tablename__ = 'country_info'

    id = Column(SmallInteger, primary_key=True)
    name = Column(String(60), nullable=False, unique=True)
    name_code = Column(String(10), nullable=True, unique=True)
    currency = Column(String(10), nullable=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    usa_country_info = session.query(CountryInfo).filter(CountryInfo.id == 1).first()
    usa_country_info.name_code = 'USA'
    session.add(usa_country_info)
    session.commit()

    op.alter_column('country_info', 'name_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_info', 'name_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
