"""Add fundamental data tables + add fields to company table

Revision ID: 7a1fc5938c84
Revises: abf207cf9b1b
Create Date: 2020-12-06 16:31:00.733168

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *


# revision identifiers, used by Alembic.
revision = '7a1fc5938c84'
down_revision = 'abf207cf9b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('assets', sa.BigInteger(), nullable=True),
    sa.Column('cashneq', sa.BigInteger(), nullable=True),
    sa.Column('investments', sa.BigInteger(), nullable=True),
    sa.Column('investmentsc', sa.BigInteger(), nullable=True),
    sa.Column('investmentsnc', sa.BigInteger(), nullable=True),
    sa.Column('deferredrev', sa.BigInteger(), nullable=True),
    sa.Column('deposits', sa.BigInteger(), nullable=True),
    sa.Column('ppnenet', sa.BigInteger(), nullable=True),
    sa.Column('inventory', sa.BigInteger(), nullable=True),
    sa.Column('taxassets', sa.BigInteger(), nullable=True),
    sa.Column('receivables', sa.BigInteger(), nullable=True),
    sa.Column('payables', sa.BigInteger(), nullable=True),
    sa.Column('intangibles', sa.BigInteger(), nullable=True),
    sa.Column('liabilities', sa.BigInteger(), nullable=True),
    sa.Column('equity', sa.BigInteger(), nullable=True),
    sa.Column('retearn', sa.BigInteger(), nullable=True),
    sa.Column('accoci', sa.BigInteger(), nullable=True),
    sa.Column('assetsc', sa.BigInteger(), nullable=True),
    sa.Column('assetsnc', sa.BigInteger(), nullable=True),
    sa.Column('liabilitiesc', sa.BigInteger(), nullable=True),
    sa.Column('liabilitiesnc', sa.BigInteger(), nullable=True),
    sa.Column('taxliabilities', sa.BigInteger(), nullable=True),
    sa.Column('debt', sa.BigInteger(), nullable=True),
    sa.Column('debtc', sa.BigInteger(), nullable=True),
    sa.Column('debtnc', sa.BigInteger(), nullable=True),
    sa.Column('equityusd', sa.BigInteger(), nullable=True),
    sa.Column('cashnequsd', sa.BigInteger(), nullable=True),
    sa.Column('debtusd', sa.BigInteger(), nullable=True),
    sa.Column('calendar_date', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.Column('period_end_date', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_balance_sheet_data_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_sheet_data'))
    )
    op.create_table('cash_flow_statement_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('capex', sa.BigInteger(), nullable=True),
    sa.Column('ncfbus', sa.BigInteger(), nullable=True),
    sa.Column('ncfinv', sa.BigInteger(), nullable=True),
    sa.Column('ncfiny', sa.BigInteger(), nullable=True),
    sa.Column('ncff', sa.BigInteger(), nullable=True),
    sa.Column('ncfdebt', sa.BigInteger(), nullable=True),
    sa.Column('ncfcommon', sa.BigInteger(), nullable=True),
    sa.Column('ncfdiv', sa.BigInteger(), nullable=True),
    sa.Column('ncfi', sa.BigInteger(), nullable=True),
    sa.Column('ncfo', sa.BigInteger(), nullable=True),
    sa.Column('ncfx', sa.BigInteger(), nullable=True),
    sa.Column('ncf', sa.BigInteger(), nullable=True),
    sa.Column('sbcomp', sa.BigInteger(), nullable=True),
    sa.Column('depamor', sa.BigInteger(), nullable=True),
    sa.Column('calendar_date', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.Column('period_end_date', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_cash_flow_statement_data_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_flow_statement_data'))
    )
    op.create_table('income_statement_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('cor', sa.BigInteger(), nullable=True),
    sa.Column('sgna', sa.BigInteger(), nullable=True),
    sa.Column('rnd', sa.BigInteger(), nullable=True),
    sa.Column('intexp', sa.BigInteger(), nullable=True),
    sa.Column('taxexp', sa.BigInteger(), nullable=True),
    sa.Column('netincdis', sa.BigInteger(), nullable=True),
    sa.Column('consolinc', sa.BigInteger(), nullable=True),
    sa.Column('netincnci', sa.BigInteger(), nullable=True),
    sa.Column('netinc', sa.BigInteger(), nullable=True),
    sa.Column('prefdivis', sa.BigInteger(), nullable=True),
    sa.Column('netinccmn', sa.BigInteger(), nullable=True),
    sa.Column('eps', sa.BigInteger(), nullable=True),
    sa.Column('epsdil', sa.BigInteger(), nullable=True),
    sa.Column('shareswa', sa.BigInteger(), nullable=True),
    sa.Column('shareswadil', sa.BigInteger(), nullable=True),
    sa.Column('ebit', sa.BigInteger(), nullable=True),
    sa.Column('epsusd', sa.BigInteger(), nullable=True),
    sa.Column('revenueusd', sa.BigInteger(), nullable=True),
    sa.Column('netinccmnusd', sa.BigInteger(), nullable=True),
    sa.Column('ebitusd', sa.BigInteger(), nullable=True),
    sa.Column('dps', sa.BigInteger(), nullable=True),
    sa.Column('gp', sa.BigInteger(), nullable=True),
    sa.Column('opinc', sa.BigInteger(), nullable=True),
    sa.Column('calendar_date', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.Column('period_end_date', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_income_statement_data_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_statement_data'))
    )
    op.add_column('company', sa.Column('shares_basic', sa.BigInteger(), nullable=True))
    op.add_column('company', sa.Column('shares_wa', sa.BigInteger(), nullable=True))
    op.add_column('company', sa.Column('shares_wa_dil', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'shares_wa_dil')
    op.drop_column('company', 'shares_wa')
    op.drop_column('company', 'shares_basic')
    op.drop_table('income_statement_data')
    op.drop_table('cash_flow_statement_data')
    op.drop_table('balance_sheet_data')
    # ### end Alembic commands ###
