"""convert exch and sectr relations tbl to class, should no nothing to db

Revision ID: 156899c26150
Revises: c642e29b8edd
Create Date: 2021-03-02 19:57:16.516944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156899c26150'
down_revision = 'c642e29b8edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
