"""note type nullable false

Revision ID: 97b07778baf7
Revises: 18cf0184cc3d
Create Date: 2021-02-28 12:24:56.830147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b07778baf7'
down_revision = '18cf0184cc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_metric_description_note', 'note_type',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_metric_description_note', 'note_type',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
