"""Add data col metric tbl

Revision ID: 711ea10f4b2b
Revises: 15e45917f5ab
Create Date: 2021-02-22 20:42:41.065624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711ea10f4b2b'
down_revision = '15e45917f5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric', sa.Column('data', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_metric', 'data')
    # ### end Alembic commands ###
