"""remove clustered idx fro bar_data, replace for single col indexes and add symbol column

Revision ID: dd76859c007a
Revises: 782a9fefd054
Create Date: 2021-01-30 15:00:00.461555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd76859c007a'
down_revision = '782a9fefd054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bar_data', sa.Column('symbol', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_bar_data_bar_date'), 'bar_data', ['bar_date'], unique=False)
    op.create_index(op.f('ix_bar_data_company_id'), 'bar_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_bar_data_symbol'), 'bar_data', ['symbol'], unique=False)
    op.drop_constraint('uq_bar_data_company_id', 'bar_data', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bar_data_company_id', 'bar_data', ['company_id', 'bar_type', 'bar_size', 'bar_date'])
    op.drop_index(op.f('ix_bar_data_symbol'), table_name='bar_data')
    op.drop_index(op.f('ix_bar_data_company_id'), table_name='bar_data')
    op.drop_index(op.f('ix_bar_data_bar_date'), table_name='bar_data')
    op.drop_column('bar_data', 'symbol')
    # ### end Alembic commands ###
