"""add acc trade tbl

Revision ID: 8c96c2b06ebc
Revises: 73d43316cbf1
Create Date: 2021-04-12 23:03:18.577211

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8c96c2b06ebc'
down_revision = '73d43316cbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(), nullable=False),
    sa.Column('asset_class', sa.String(length=10), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=10), nullable=True),
    sa.Column('symbol', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('trade_type', sa.SmallInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('strike', sa.Integer(), nullable=True),
    sa.Column('is_call', sa.Boolean(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('trade_price', sa.Numeric(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('commission_currency', sa.String(length=20), nullable=False),
    sa.Column('cost_basis', sa.Numeric(), nullable=False),
    sa.Column('proceeds', sa.Numeric(), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_trade'))
    )
    op.create_index(op.f('ix_account_trade_asset_class'), 'account_trade', ['asset_class'], unique=False)
    op.create_index(op.f('ix_account_trade_commission_currency'), 'account_trade', ['commission_currency'], unique=False)
    op.create_index(op.f('ix_account_trade_currency'), 'account_trade', ['currency'], unique=False)
    op.create_index(op.f('ix_account_trade_expiry'), 'account_trade', ['expiry'], unique=False)
    op.create_index(op.f('ix_account_trade_symbol'), 'account_trade', ['symbol'], unique=False)
    op.create_index(op.f('ix_account_trade_trade_date'), 'account_trade', ['trade_date'], unique=False)
    op.create_index(op.f('ix_account_trade_trade_type'), 'account_trade', ['trade_type'], unique=False)
    op.create_index(op.f('ix_account_trade_underlying_symbol'), 'account_trade', ['underlying_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_trade_underlying_symbol'), table_name='account_trade')
    op.drop_index(op.f('ix_account_trade_trade_type'), table_name='account_trade')
    op.drop_index(op.f('ix_account_trade_trade_date'), table_name='account_trade')
    op.drop_index(op.f('ix_account_trade_symbol'), table_name='account_trade')
    op.drop_index(op.f('ix_account_trade_expiry'), table_name='account_trade')
    op.drop_index(op.f('ix_account_trade_currency'), table_name='account_trade')
    op.drop_index(op.f('ix_account_trade_commission_currency'), table_name='account_trade')
    op.drop_index(op.f('ix_account_trade_asset_class'), table_name='account_trade')
    op.drop_table('account_trade')
    # ### end Alembic commands ###
