"""new bar data table

Revision ID: 1fcdbb9f2187
Revises: 87f0111e5801
Create Date: 2021-01-31 22:11:20.246509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fcdbb9f2187'
down_revision = '87f0111e5801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_bar_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('bar_type', sa.Integer(), nullable=False),
    sa.Column('bar_open', sa.Numeric(), nullable=False),
    sa.Column('bar_high', sa.Numeric(), nullable=False),
    sa.Column('bar_low', sa.Numeric(), nullable=False),
    sa.Column('bar_close', sa.Numeric(), nullable=False),
    sa.Column('bar_volume', sa.BigInteger(), nullable=True),
    sa.Column('bar_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bar_size', sa.String(length=12), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency_bar_data'))
    )
    op.create_index(op.f('ix_currency_bar_data_bar_date'), 'currency_bar_data', ['bar_date'], unique=False)
    op.create_index(op.f('ix_currency_bar_data_symbol'), 'currency_bar_data', ['symbol'], unique=False)
    op.create_table('equity_bar_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.SmallInteger(), nullable=False),
    sa.Column('bar_type', sa.Integer(), nullable=False),
    sa.Column('bar_open', sa.Numeric(), nullable=False),
    sa.Column('bar_high', sa.Numeric(), nullable=False),
    sa.Column('bar_low', sa.Numeric(), nullable=False),
    sa.Column('bar_close', sa.Numeric(), nullable=False),
    sa.Column('bar_volume', sa.BigInteger(), nullable=True),
    sa.Column('bar_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bar_size', sa.String(length=12), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_equity_bar_data_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name=op.f('fk_equity_bar_data_exchange_id_exchange'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equity_bar_data'))
    )
    op.create_index(op.f('ix_equity_bar_data_bar_date'), 'equity_bar_data', ['bar_date'], unique=False)
    op.create_index(op.f('ix_equity_bar_data_company_id'), 'equity_bar_data', ['company_id'], unique=False)
    op.drop_index('ix_bar_data_bar_date', table_name='bar_data')
    op.drop_index('ix_bar_data_company_id', table_name='bar_data')
    op.drop_index('ix_bar_data_symbol', table_name='bar_data')
    op.drop_table('bar_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('bar_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bar_open', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_high', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_low', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_close', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bar_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('bar_size', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_bar_data_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name='fk_bar_data_exchange_id_exchange', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_bar_data')
    )
    op.create_index('ix_bar_data_symbol', 'bar_data', ['symbol'], unique=False)
    op.create_index('ix_bar_data_company_id', 'bar_data', ['company_id'], unique=False)
    op.create_index('ix_bar_data_bar_date', 'bar_data', ['bar_date'], unique=False)
    op.drop_index(op.f('ix_equity_bar_data_company_id'), table_name='equity_bar_data')
    op.drop_index(op.f('ix_equity_bar_data_bar_date'), table_name='equity_bar_data')
    op.drop_table('equity_bar_data')
    op.drop_index(op.f('ix_currency_bar_data_symbol'), table_name='currency_bar_data')
    op.drop_index(op.f('ix_currency_bar_data_bar_date'), table_name='currency_bar_data')
    op.drop_table('currency_bar_data')
    # ### end Alembic commands ###
