"""remove calculated cols from inc statement

Revision ID: 87f0111e5801
Revises: dd76859c007a
Create Date: 2021-01-30 17:13:29.233773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f0111e5801'
down_revision = 'dd76859c007a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_statement_data', 'gp')
    op.drop_column('income_statement_data', 'dps')
    op.drop_column('income_statement_data', 'opinc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_statement_data', sa.Column('opinc', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('income_statement_data', sa.Column('dps', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('income_statement_data', sa.Column('gp', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
