"""remove exch id column from bar data idx

Revision ID: 3dc3591e0bf5
Revises: 9d28aacf5f20
Create Date: 2021-01-13 21:14:42.267709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc3591e0bf5'
down_revision = '9d28aacf5f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bar_data_company_id', 'bar_data', type_='unique')
    op.create_unique_constraint(op.f('uq_bar_data_company_id'), 'bar_data', ['company_id', 'bar_type', 'bar_size', 'bar_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bar_data_company_id'), 'bar_data', type_='unique')
    op.create_unique_constraint('uq_bar_data_company_id', 'bar_data', ['company_id', 'bar_type', 'bar_size', 'bar_date', 'exchange_id'])
    # ### end Alembic commands ###
