"""symbol nullable false

Revision ID: 57af6e46be1b
Revises: 1fcdbb9f2187
Create Date: 2021-01-31 22:29:38.033490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57af6e46be1b'
down_revision = '1fcdbb9f2187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_bar_data', 'symbol',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_bar_data', 'symbol',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###
