"""fix metrics tbls

Revision ID: c5ed198a4fc7
Revises: 711ea10f4b2b
Create Date: 2021-02-25 16:47:50.678560

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *


# revision identifiers, used by Alembic.
revision = 'c5ed198a4fc7'
down_revision = '711ea10f4b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metric_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('metric_data_type', sa.SmallInteger(), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_metric_description_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metric_description')),
    sa.UniqueConstraint('code', name=op.f('uq_company_metric_description_code')),
    sa.UniqueConstraint('display_name', name=op.f('uq_company_metric_description_display_name'))
    )
    op.create_index(op.f('ix_company_metric_description_company_id'), 'company_metric_description', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_metric_description_update_stamp'), 'company_metric_description', ['update_stamp'], unique=False)
    op.add_column('company_metric', sa.Column('company_metric_description_id', sa.Integer(), nullable=False))
    op.add_column('company_metric', sa.Column('definition', sa.String(length=500), nullable=False))
    op.alter_column('company_metric', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               autoincrement=True)
    op.create_index(op.f('ix_company_metric_company_metric_description_id'), 'company_metric', ['company_metric_description_id'], unique=False)
    op.drop_index('ix_company_metric_code', table_name='company_metric')
    op.drop_index('ix_company_metric_company_id', table_name='company_metric')
    op.drop_index('ix_company_metric_metric_type', table_name='company_metric')
    op.drop_constraint('fk_company_metric_company_id_company', 'company_metric', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_metric_company_metric_description_id_company_metric_description'), 'company_metric', 'company_metric_description', ['company_metric_description_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_metric', 'code')
    op.drop_column('company_metric', 'display_name')
    op.drop_column('company_metric', 'metric_type')
    op.drop_column('company_metric', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('company_metric', sa.Column('metric_type', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('company_metric', sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('company_metric', sa.Column('code', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_metric_company_metric_description_id_company_metric_description'), 'company_metric', type_='foreignkey')
    op.create_foreign_key('fk_company_metric_company_id_company', 'company_metric', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_metric_metric_type', 'company_metric', ['metric_type'], unique=False)
    op.create_index('ix_company_metric_company_id', 'company_metric', ['company_id'], unique=False)
    op.create_index('ix_company_metric_code', 'company_metric', ['code'], unique=False)
    op.drop_index(op.f('ix_company_metric_company_metric_description_id'), table_name='company_metric')
    op.alter_column('company_metric', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               autoincrement=True)
    op.drop_column('company_metric', 'definition')
    op.drop_column('company_metric', 'company_metric_description_id')
    op.drop_index(op.f('ix_company_metric_description_update_stamp'), table_name='company_metric_description')
    op.drop_index(op.f('ix_company_metric_description_company_id'), table_name='company_metric_description')
    op.drop_table('company_metric_description')
    # ### end Alembic commands ###
