"""new tbls + rework

Revision ID: 904e7631943e
Revises: 2121be493849
Create Date: 2021-03-09 19:00:13.927460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '904e7631943e'
down_revision = '2121be493849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_business_or_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_business_or_product_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_business_or_product'))
    )
    op.create_index(op.f('ix_company_business_or_product_company_id'), 'company_business_or_product', ['company_id'], unique=False)
    op.add_column('company_development', sa.Column('code', sa.String(length=60), nullable=False))
    op.add_column('company_development', sa.Column('company_business_or_product', sa.Integer(), nullable=False))
    op.alter_column('company_development', 'date_recorded',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_company_development_company_business_or_product'), 'company_development', ['company_business_or_product'], unique=False)
    op.drop_index('ix_company_development_company_id', table_name='company_development')
    op.drop_constraint('fk_company_development_company_id_company', 'company_development', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_development_company_business_or_product_company_business_or_product'), 'company_development', 'company_business_or_product', ['company_business_or_product'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_development', 'company_id')
    op.add_column('company_metric', sa.Column('company_business_or_product', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_company_metric_company_business_or_product'), 'company_metric', ['company_business_or_product'], unique=False)
    op.drop_index('ix_company_metric_company_id', table_name='company_metric')
    op.drop_constraint('fk_company_metric_company_id_company', 'company_metric', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_metric_company_business_or_product_company_business_or_product'), 'company_metric', 'company_business_or_product', ['company_business_or_product'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_metric', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_metric_company_business_or_product_company_business_or_product'), 'company_metric', type_='foreignkey')
    op.create_foreign_key('fk_company_metric_company_id_company', 'company_metric', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_metric_company_id', 'company_metric', ['company_id'], unique=False)
    op.drop_index(op.f('ix_company_metric_company_business_or_product'), table_name='company_metric')
    op.drop_column('company_metric', 'company_business_or_product')
    op.add_column('company_development', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_development_company_business_or_product_company_business_or_product'), 'company_development', type_='foreignkey')
    op.create_foreign_key('fk_company_development_company_id_company', 'company_development', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_development_company_id', 'company_development', ['company_id'], unique=False)
    op.drop_index(op.f('ix_company_development_company_business_or_product'), table_name='company_development')
    op.alter_column('company_development', 'date_recorded',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('company_development', 'company_business_or_product')
    op.drop_column('company_development', 'code')
    op.drop_index(op.f('ix_company_business_or_product_company_id'), table_name='company_business_or_product')
    op.drop_table('company_business_or_product')
    # ### end Alembic commands ###
