"""remove usd cols from fundamental data tables

Revision ID: 782a9fefd054
Revises: b2affe853001
Create Date: 2021-01-30 14:29:59.265164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782a9fefd054'
down_revision = 'b2affe853001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_sheet_data', 'debtusd')
    op.drop_column('balance_sheet_data', 'equityusd')
    op.drop_column('balance_sheet_data', 'cashnequsd')
    op.add_column('income_statement_data', sa.Column('opex', sa.BigInteger(), nullable=True))
    op.drop_column('income_statement_data', 'eps')
    op.drop_column('income_statement_data', 'epsusd')
    op.drop_column('income_statement_data', 'ebit')
    op.drop_column('income_statement_data', 'epsdil')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_statement_data', sa.Column('epsdil', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('income_statement_data', sa.Column('ebit', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('income_statement_data', sa.Column('epsusd', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('income_statement_data', sa.Column('eps', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('income_statement_data', 'opex')
    op.add_column('balance_sheet_data', sa.Column('cashnequsd', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('balance_sheet_data', sa.Column('equityusd', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('balance_sheet_data', sa.Column('debtusd', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
