"""rename

Revision ID: c7fd3782bc09
Revises: 3ed2a1f838cb
Create Date: 2021-03-01 20:37:57.820521

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *

# revision identifiers, used by Alembic.
revision = 'c7fd3782bc09'
down_revision = '3ed2a1f838cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metric_relation',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_metric_description_id', sa.Integer(), nullable=False),
    sa.Column('company_metric_description_note_id', sa.Integer(), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_metric_relation_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name=op.f('fk_company_metric_relation_company_metric_description_id_company_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_note_id'], ['company_metric_description_note.id'], name=op.f('fk_company_metric_relation_company_metric_description_note_id_company_metric_description_note'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'company_metric_description_id', 'company_metric_description_note_id', name=op.f('pk_company_metric_relation'))
    )
    op.create_index(op.f('ix_company_metric_relation_update_stamp'), 'company_metric_relation', ['update_stamp'], unique=False)
    op.drop_index('ix_company_metrics_relation_update_stamp', table_name='company_metrics_relation')
    op.drop_table('company_metrics_relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metrics_relation',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_metric_description_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_metric_description_note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_metrics_relation_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name='fk_company_metrics_relation_company_metric_description__44d7', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_note_id'], ['company_metric_description_note.id'], name='fk_company_metrics_relation_company_metric_description__12c6', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'company_metric_description_id', 'company_metric_description_note_id', name='pk_company_metrics_relation')
    )
    op.create_index('ix_company_metrics_relation_update_stamp', 'company_metrics_relation', ['update_stamp'], unique=False)
    op.drop_index(op.f('ix_company_metric_relation_update_stamp'), table_name='company_metric_relation')
    op.drop_table('company_metric_relation')
    # ### end Alembic commands ###
