"""create company group relation and add industry id to company tbl

Revision ID: 73d43316cbf1
Revises: 3924991a0f07
Create Date: 2021-03-29 21:46:27.355044

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '73d43316cbf1'
down_revision = '3924991a0f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_group_relation',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_group_relation_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['company_group.id'], name=op.f('fk_company_group_relation_group_id_company_group'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'group_id', name=op.f('pk_company_group_relation'))
    )
    op.add_column('company', sa.Column('industry_id', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_company_industry_id'), 'company', ['industry_id'], unique=False)
    op.drop_index('ix_company_group_id', table_name='company')
    op.drop_constraint('fk_company_group_id_company_group', 'company', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_industry_id_industry'), 'company', 'industry', ['industry_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_company_industry_id_industry'), 'company', type_='foreignkey')
    op.create_foreign_key('fk_company_group_id_company_group', 'company', 'company_group', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_group_id', 'company', ['group_id'], unique=False)
    op.drop_index(op.f('ix_company_industry_id'), table_name='company')
    op.drop_column('company', 'industry_id')
    op.drop_table('company_group_relation')
    # ### end Alembic commands ###
