"""create relation tbl between all metrics tbl

Revision ID: 3ed2a1f838cb
Revises: 97b07778baf7
Create Date: 2021-03-01 20:34:08.104298

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *


# revision identifiers, used by Alembic.
revision = '3ed2a1f838cb'
down_revision = '97b07778baf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metrics_relation',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_metric_description_id', sa.Integer(), nullable=False),
    sa.Column('company_metric_description_note_id', sa.Integer(), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_metrics_relation_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name=op.f('fk_company_metrics_relation_company_metric_description_id_company_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_note_id'], ['company_metric_description_note.id'], name=op.f('fk_company_metrics_relation_company_metric_description_note_id_company_metric_description_note'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'company_metric_description_id', 'company_metric_description_note_id', name=op.f('pk_company_metrics_relation'))
    )
    op.create_index(op.f('ix_company_metrics_relation_update_stamp'), 'company_metrics_relation', ['update_stamp'], unique=False)
    op.drop_index('ix_company_metric_description_note_company_id', table_name='company_metric_description_note')
    op.drop_index('ix_company_metric_description_note_company_metric_descr_1449', table_name='company_metric_description_note')
    op.drop_constraint('fk_company_metric_description_note_company_id_company', 'company_metric_description_note', type_='foreignkey')
    op.drop_constraint('fk_company_metric_description_note_company_metric_descr_c06d', 'company_metric_description_note', type_='foreignkey')
    op.drop_column('company_metric_description_note', 'company_metric_description_id')
    op.drop_column('company_metric_description_note', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric_description_note', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company_metric_description_note', sa.Column('company_metric_description_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_company_metric_description_note_company_metric_descr_c06d', 'company_metric_description_note', 'company_metric_description', ['company_metric_description_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_company_metric_description_note_company_id_company', 'company_metric_description_note', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_metric_description_note_company_metric_descr_1449', 'company_metric_description_note', ['company_metric_description_id'], unique=False)
    op.create_index('ix_company_metric_description_note_company_id', 'company_metric_description_note', ['company_id'], unique=False)
    op.drop_index(op.f('ix_company_metrics_relation_update_stamp'), table_name='company_metrics_relation')
    op.drop_table('company_metrics_relation')
    # ### end Alembic commands ###
