"""rework financial tables

Revision ID: 9602723d194b
Revises: 57af6e46be1b
Create Date: 2021-02-17 21:49:59.378450

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *

# revision identifiers, used by Alembic.
revision = '9602723d194b'
down_revision = '57af6e46be1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_quarterly_financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('assets', sa.BigInteger(), nullable=True),
    sa.Column('cashneq', sa.BigInteger(), nullable=True),
    sa.Column('investments', sa.BigInteger(), nullable=True),
    sa.Column('investmentsc', sa.BigInteger(), nullable=True),
    sa.Column('investmentsnc', sa.BigInteger(), nullable=True),
    sa.Column('deferredrev', sa.BigInteger(), nullable=True),
    sa.Column('deposits', sa.BigInteger(), nullable=True),
    sa.Column('ppnenet', sa.BigInteger(), nullable=True),
    sa.Column('inventory', sa.BigInteger(), nullable=True),
    sa.Column('taxassets', sa.BigInteger(), nullable=True),
    sa.Column('receivables', sa.BigInteger(), nullable=True),
    sa.Column('payables', sa.BigInteger(), nullable=True),
    sa.Column('intangibles', sa.BigInteger(), nullable=True),
    sa.Column('liabilities', sa.BigInteger(), nullable=True),
    sa.Column('equity', sa.BigInteger(), nullable=True),
    sa.Column('retearn', sa.BigInteger(), nullable=True),
    sa.Column('accoci', sa.BigInteger(), nullable=True),
    sa.Column('assetsc', sa.BigInteger(), nullable=True),
    sa.Column('assetsnc', sa.BigInteger(), nullable=True),
    sa.Column('liabilitiesc', sa.BigInteger(), nullable=True),
    sa.Column('liabilitiesnc', sa.BigInteger(), nullable=True),
    sa.Column('taxliabilities', sa.BigInteger(), nullable=True),
    sa.Column('debt', sa.BigInteger(), nullable=True),
    sa.Column('debtc', sa.BigInteger(), nullable=True),
    sa.Column('debtnc', sa.BigInteger(), nullable=True),
    sa.Column('calendar_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_filed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('cor', sa.BigInteger(), nullable=True),
    sa.Column('opex', sa.BigInteger(), nullable=True),
    sa.Column('sgna', sa.BigInteger(), nullable=True),
    sa.Column('rnd', sa.BigInteger(), nullable=True),
    sa.Column('intexp', sa.BigInteger(), nullable=True),
    sa.Column('taxexp', sa.BigInteger(), nullable=True),
    sa.Column('netincdis', sa.BigInteger(), nullable=True),
    sa.Column('consolinc', sa.BigInteger(), nullable=True),
    sa.Column('netincnci', sa.BigInteger(), nullable=True),
    sa.Column('netinc', sa.BigInteger(), nullable=True),
    sa.Column('prefdivis', sa.BigInteger(), nullable=True),
    sa.Column('netinccmn', sa.BigInteger(), nullable=True),
    sa.Column('capex', sa.BigInteger(), nullable=True),
    sa.Column('ncfbus', sa.BigInteger(), nullable=True),
    sa.Column('ncfi', sa.BigInteger(), nullable=True),
    sa.Column('ncfinv', sa.BigInteger(), nullable=True),
    sa.Column('ncff', sa.BigInteger(), nullable=True),
    sa.Column('ncfdebt', sa.BigInteger(), nullable=True),
    sa.Column('ncfcommon', sa.BigInteger(), nullable=True),
    sa.Column('ncfdiv', sa.BigInteger(), nullable=True),
    sa.Column('ncfo', sa.BigInteger(), nullable=True),
    sa.Column('ncfx', sa.BigInteger(), nullable=True),
    sa.Column('ncf', sa.BigInteger(), nullable=True),
    sa.Column('sbcomp', sa.BigInteger(), nullable=True),
    sa.Column('depamor', sa.BigInteger(), nullable=True),
    sa.Column('sharesbas', sa.BigInteger(), nullable=True),
    sa.Column('shareswa', sa.BigInteger(), nullable=True),
    sa.Column('shareswadil', sa.BigInteger(), nullable=True),
    sa.Column('fx_usd', sa.Numeric(), nullable=True),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_quarterly_financial_data_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_quarterly_financial_data'))
    )
    op.create_index(op.f('ix_company_quarterly_financial_data_calendar_date'), 'company_quarterly_financial_data', ['calendar_date'], unique=False)
    op.create_index(op.f('ix_company_quarterly_financial_data_company_id'), 'company_quarterly_financial_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_quarterly_financial_data_date_filed'), 'company_quarterly_financial_data', ['date_filed'], unique=False)
    op.drop_index('ix_balance_sheet_data_calendar_date', table_name='balance_sheet_data')
    op.drop_index('ix_balance_sheet_data_company_id', table_name='balance_sheet_data')
    op.drop_index('ix_balance_sheet_data_date_filed', table_name='balance_sheet_data')
    op.drop_table('balance_sheet_data')
    op.drop_index('ix_income_statement_data_calendar_date', table_name='income_statement_data')
    op.drop_index('ix_income_statement_data_company_id', table_name='income_statement_data')
    op.drop_index('ix_income_statement_data_date_filed', table_name='income_statement_data')
    op.drop_table('income_statement_data')
    op.drop_index('ix_company_misc_info_company_id', table_name='company_misc_info')
    op.drop_index('ix_company_misc_info_date_recorded', table_name='company_misc_info')
    op.drop_table('company_misc_info')
    op.drop_index('ix_cash_flow_statement_data_calendar_date', table_name='cash_flow_statement_data')
    op.drop_index('ix_cash_flow_statement_data_company_id', table_name='cash_flow_statement_data')
    op.drop_index('ix_cash_flow_statement_data_date_filed', table_name='cash_flow_statement_data')
    op.drop_table('cash_flow_statement_data')
    op.add_column('company_fundamental_ratios', sa.Column('capexps_current', sa.Numeric(), nullable=True))
    op.drop_column('company_fundamental_ratios', 'capexps__current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_fundamental_ratios', sa.Column('capexps__current', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('company_fundamental_ratios', 'capexps_current')
    op.create_table('cash_flow_statement_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capex', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfbus', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfinv', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncff', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfdebt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfcommon', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfdiv', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfi', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfo', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncfx', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ncf', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sbcomp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('depamor', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('calendar_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_filed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_cash_flow_statement_data_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_cash_flow_statement_data')
    )
    op.create_index('ix_cash_flow_statement_data_date_filed', 'cash_flow_statement_data', ['date_filed'], unique=False)
    op.create_index('ix_cash_flow_statement_data_company_id', 'cash_flow_statement_data', ['company_id'], unique=False)
    op.create_index('ix_cash_flow_statement_data_calendar_date', 'cash_flow_statement_data', ['calendar_date'], unique=False)
    op.create_table('company_misc_info',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shares_bas', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shares_dil', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('date_recorded', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('occurence', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_misc_info_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_misc_info')
    )
    op.create_index('ix_company_misc_info_date_recorded', 'company_misc_info', ['date_recorded'], unique=False)
    op.create_index('ix_company_misc_info_company_id', 'company_misc_info', ['company_id'], unique=False)
    op.create_table('income_statement_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cor', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sgna', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rnd', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('intexp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('taxexp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('netincdis', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('consolinc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('netincnci', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('netinc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('prefdivis', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('netinccmn', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shareswa', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shareswadil', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('calendar_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_filed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('opex', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_income_statement_data_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_income_statement_data')
    )
    op.create_index('ix_income_statement_data_date_filed', 'income_statement_data', ['date_filed'], unique=False)
    op.create_index('ix_income_statement_data_company_id', 'income_statement_data', ['company_id'], unique=False)
    op.create_index('ix_income_statement_data_calendar_date', 'income_statement_data', ['calendar_date'], unique=False)
    op.create_table('balance_sheet_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assets', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cashneq', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('investments', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('investmentsc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('investmentsnc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('deferredrev', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('deposits', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ppnenet', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('inventory', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('taxassets', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('receivables', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payables', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('intangibles', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('liabilities', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('equity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('retearn', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('accoci', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('assetsc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('assetsnc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('liabilitiesc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('liabilitiesnc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('taxliabilities', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('debt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('debtc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('debtnc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('calendar_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_filed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_balance_sheet_data_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_balance_sheet_data')
    )
    op.create_index('ix_balance_sheet_data_date_filed', 'balance_sheet_data', ['date_filed'], unique=False)
    op.create_index('ix_balance_sheet_data_company_id', 'balance_sheet_data', ['company_id'], unique=False)
    op.create_index('ix_balance_sheet_data_calendar_date', 'balance_sheet_data', ['calendar_date'], unique=False)
    op.drop_index(op.f('ix_company_quarterly_financial_data_date_filed'), table_name='company_quarterly_financial_data')
    op.drop_index(op.f('ix_company_quarterly_financial_data_company_id'), table_name='company_quarterly_financial_data')
    op.drop_index(op.f('ix_company_quarterly_financial_data_calendar_date'), table_name='company_quarterly_financial_data')
    op.drop_table('company_quarterly_financial_data')
    # ### end Alembic commands ###
