"""note_data is now binary

Revision ID: 8a6a8989d9b1
Revises: dd7c8a730f79
Create Date: 2021-02-25 20:40:05.918879

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *


# revision identifiers, used by Alembic.
revision = '8a6a8989d9b1'
down_revision = 'dd7c8a730f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metric_description_note',
    sa.Column('company_metric_description_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_data', sa.LargeBinary(), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name=op.f('fk_company_metric_description_note_company_metric_description_id_company_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metric_description_note'))
    )
    op.create_index(op.f('ix_company_metric_description_note_company_metric_description_id'), 'company_metric_description_note', ['company_metric_description_id'], unique=False)
    op.create_index(op.f('ix_company_metric_description_note_update_stamp'), 'company_metric_description_note', ['update_stamp'], unique=False)
    op.drop_column('company_metric_description', 'definition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric_description', sa.Column('definition', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_company_metric_description_note_update_stamp'), table_name='company_metric_description_note')
    op.drop_index(op.f('ix_company_metric_description_note_company_metric_description_id'), table_name='company_metric_description_note')
    op.drop_table('company_metric_description_note')
    # ### end Alembic commands ###
