"""add company_id to metric tbl

Revision ID: b7cf61ae1173
Revises: 2d9062f37c08
Create Date: 2021-02-28 11:44:19.701371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cf61ae1173'
down_revision = '2d9062f37c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_metric_company_id'), 'company_metric', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_company_metric_company_id_company'), 'company_metric', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_company_metric_company_id_company'), 'company_metric', type_='foreignkey')
    op.drop_index(op.f('ix_company_metric_company_id'), table_name='company_metric')
    op.drop_column('company_metric', 'company_id')
    # ### end Alembic commands ###
