"""remove uq constrait on display name

Revision ID: 9d87f64757e0
Revises: a3b37ca03c06
Create Date: 2021-02-25 21:04:49.710538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d87f64757e0'
down_revision = 'a3b37ca03c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_metric_description_display_name', 'company_metric_description', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_company_metric_description_display_name', 'company_metric_description', ['display_name'])
    # ### end Alembic commands ###
