"""chaneg finacial data tbl name

Revision ID: cd2dee2a8e58
Revises: 9761c285cb91
Create Date: 2021-03-27 17:58:51.993750

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'cd2dee2a8e58'
down_revision = '9761c285cb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_group')),
    sa.UniqueConstraint('name', name=op.f('uq_company_group_name')),
    sa.UniqueConstraint('name_code', name=op.f('uq_company_group_name_code'))
    )
    op.add_column('company', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_group_id'), 'company', ['group_id'], unique=False)
    op.create_foreign_key(op.f('fk_company_group_id_company_group'), 'company', 'company_group', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('company_quarterly_financial_data', sa.Column('data_type', sa.SmallInteger(), nullable=True))
    op.add_column('company_quarterly_financial_data', sa.Column('effective_tax_rate', sa.Numeric(), nullable=True))
    op.execute('ALTER TABLE company_quarterly_financial_data RENAME TO company_financial_data;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_quarterly_financial_data', 'effective_tax_rate')
    op.drop_column('company_quarterly_financial_data', 'data_type')
    op.drop_constraint(op.f('fk_company_group_id_company_group'), 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_group_id'), table_name='company')
    op.drop_column('company', 'group_id')
    op.drop_table('company_group')
    op.execute('ALTER TABLE company_financial_data RENAME TO company_quarterly_financial_data;')
    # ### end Alembic commands ###
