"""add def col

Revision ID: dd7c8a730f79
Revises: 8182e32dbf5a
Create Date: 2021-02-25 17:17:20.882511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7c8a730f79'
down_revision = '8182e32dbf5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_metric', 'definition')
    op.add_column('company_metric_description', sa.Column('definition', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_metric_description', 'definition')
    op.add_column('company_metric', sa.Column('definition', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
