"""add note type

Revision ID: 18cf0184cc3d
Revises: b7cf61ae1173
Create Date: 2021-02-28 12:24:15.283215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cf0184cc3d'
down_revision = 'b7cf61ae1173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric_description_note', sa.Column('note_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_metric_description_note', 'note_type')
    # ### end Alembic commands ###
