"""unique si now clustered in metric_desc

Revision ID: a3b37ca03c06
Revises: 66586ad2b1b1
Create Date: 2021-02-25 21:03:25.244109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b37ca03c06'
down_revision = '66586ad2b1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_company_metric_description_company_id'), 'company_metric_description', ['company_id', 'code'])
    op.drop_constraint('uq_company_metric_description_code', 'company_metric_description', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_company_metric_description_code', 'company_metric_description', ['code'])
    op.drop_constraint(op.f('uq_company_metric_description_company_id'), 'company_metric_description', type_='unique')
    # ### end Alembic commands ###
