"""cahnged pk to unique cosntraitn in metric relation tbk

Revision ID: c3b655948ceb
Revises: 97b07778baf7
Create Date: 2021-03-04 17:07:46.921797

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy import *
from sqlalchemy import orm
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3b655948ceb'
down_revision = '97b07778baf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metric_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_metric_description_id', sa.Integer(), nullable=False),
    sa.Column('company_metric_description_note_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('update_stamp', sa.DateTime(timezone=True), server_default=FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_metric_relation_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name=op.f('fk_company_metric_relation_company_metric_description_id_company_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_note_id'], ['company_metric_description_note.id'], name=op.f('fk_company_metric_relation_company_metric_description_note_id_company_metric_description_note'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metric_relation')),
    sa.UniqueConstraint('company_metric_description_id', 'company_metric_description_note_id', 'company_id', name=op.f('uq_company_metric_relation_company_metric_description_id'))
    )
    op.create_index(op.f('ix_company_metric_relation_update_stamp'), 'company_metric_relation', ['update_stamp'], unique=False)
    op.alter_column('company_metric', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_metric', 'date_recorded',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_index('ix_company_metric_description_note_company_id', table_name='company_metric_description_note')
    op.drop_index('ix_company_metric_description_note_company_metric_descr_1449', table_name='company_metric_description_note')
    op.drop_constraint('fk_company_metric_description_note_company_id_company', 'company_metric_description_note', type_='foreignkey')
    op.drop_constraint('fk_company_metric_description_note_company_metric_descr_c06d', 'company_metric_description_note', type_='foreignkey')
    op.drop_column('company_metric_description_note', 'company_id')
    op.drop_column('company_metric_description_note', 'company_metric_description_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric_description_note', sa.Column('company_metric_description_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company_metric_description_note', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_company_metric_description_note_company_metric_descr_c06d', 'company_metric_description_note', 'company_metric_description', ['company_metric_description_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_company_metric_description_note_company_id_company', 'company_metric_description_note', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_metric_description_note_company_metric_descr_1449', 'company_metric_description_note', ['company_metric_description_id'], unique=False)
    op.create_index('ix_company_metric_description_note_company_id', 'company_metric_description_note', ['company_id'], unique=False)
    op.alter_column('company_metric', 'date_recorded',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('company_metric', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_company_metric_relation_update_stamp'), table_name='company_metric_relation')
    op.drop_table('company_metric_relation')
    # ### end Alembic commands ###
