"""set nullable industry_id in company_group

Revision ID: a479c9da906a
Revises: ad10c7af3bdd
Create Date: 2022-05-16 20:17:09.378276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a479c9da906a'
down_revision = 'ad10c7af3bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_group', 'industry_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_group', 'industry_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
