"""add creator_id column to bus segment table

Revision ID: 30cbf4715d8e
Revises: 22317c1e0fff
Create Date: 2022-10-19 23:25:04.826876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cbf4715d8e'
down_revision = '22317c1e0fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_business_segment', sa.Column('creator_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(op.f('fk_company_business_segment_creator_id_account'), 'company_business_segment', 'account', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_company_business_segment_creator_id_account'), 'company_business_segment', type_='foreignkey')
    op.drop_column('company_business_segment', 'creator_id')
    # ### end Alembic commands ###
