"""remove uq constraint pwd column acc table

Revision ID: 0a6aa1674763
Revises: 204557a565f0
Create Date: 2022-08-30 08:09:52.627955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6aa1674763'
down_revision = '204557a565f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_password', 'account', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_account_password', 'account', ['password'])
    # ### end Alembic commands ###
