"""set user_id to not nullable in metric_data

Revision ID: c2d8dab4326c
Revises: cdfc13f1f06c
Create Date: 2022-10-08 21:17:15.786457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d8dab4326c'
down_revision = 'cdfc13f1f06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metric_data', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_metric_data_metric_description_id'), 'metric_data', ['metric_description_id', 'company_business_segment_id', 'user_id'])
    # ### end Alembic commands ###

    op.alter_column('user_metric_description', 'account_id',
               existing_type=sa.BIGINT(),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_metric_data_metric_description_id'), 'metric_data', type_='unique')
    op.alter_column('metric_data', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
    op.alter_column('user_metric_description', 'account_id',
               existing_type=sa.BIGINT(),
               nullable=True)
