"""remove unused tables

Revision ID: 29a2cfc8fc42
Revises: 184e1497fc87
Create Date: 2022-10-24 20:43:48.764916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29a2cfc8fc42'
down_revision = '184e1497fc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_summary_company_id', table_name='company_summary')
    op.drop_table('company_summary')
    op.drop_index('ix_currency_bar_data_bar_date', table_name='currency_bar_data')
    op.drop_index('ix_currency_bar_data_symbol', table_name='currency_bar_data')
    op.drop_table('currency_bar_data')
    op.drop_index('ix_account_trade_asset_class', table_name='account_trade')
    op.drop_index('ix_account_trade_brokerage_id', table_name='account_trade')
    op.drop_index('ix_account_trade_commission_currency', table_name='account_trade')
    op.drop_index('ix_account_trade_currency', table_name='account_trade')
    op.drop_index('ix_account_trade_expiry', table_name='account_trade')
    op.drop_index('ix_account_trade_symbol', table_name='account_trade')
    op.drop_index('ix_account_trade_trade_date', table_name='account_trade')
    op.drop_index('ix_account_trade_trade_type', table_name='account_trade')
    op.drop_index('ix_account_trade_underlying_symbol', table_name='account_trade')
    op.drop_table('account_trade')
    op.drop_index('ix_equity_bar_data_bar_date', table_name='equity_bar_data')
    op.drop_index('ix_equity_bar_data_company_id', table_name='equity_bar_data')
    op.drop_table('equity_bar_data')
    op.drop_index('ix_company_development_company_business_segment_id', table_name='company_development')
    op.drop_index('ix_company_development_data_type', table_name='company_development')
    op.drop_index('ix_company_development_date_recorded', table_name='company_development')
    op.drop_index('ix_company_development_dev_type', table_name='company_development')
    op.drop_table('company_development')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_development',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('dev_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_recorded', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('company_business_segment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_business_segment_id'], ['company_business_segment.id'], name='fk_company_development_company_business_segment_id_comp_375e', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_development')
    )
    op.create_index('ix_company_development_dev_type', 'company_development', ['dev_type'], unique=False)
    op.create_index('ix_company_development_date_recorded', 'company_development', ['date_recorded'], unique=False)
    op.create_index('ix_company_development_data_type', 'company_development', ['data_type'], unique=False)
    op.create_index('ix_company_development_company_business_segment_id', 'company_development', ['company_business_segment_id'], unique=False)
    op.create_table('equity_bar_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bar_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bar_open', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_high', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_low', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_close', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bar_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('bar_size', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_equity_bar_data_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name='fk_equity_bar_data_exchange_id_exchange', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_equity_bar_data')
    )
    op.create_index('ix_equity_bar_data_company_id', 'equity_bar_data', ['company_id'], unique=False)
    op.create_index('ix_equity_bar_data_bar_date', 'equity_bar_data', ['bar_date'], unique=False)
    op.create_table('account_trade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fx_rate_to_base', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('asset_class', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('underlying_symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('trade_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('strike', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_call', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('multiplier', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trade_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('commission', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('commission_currency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cost_basis', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('proceeds', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('brokerage_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_trade')
    )
    op.create_index('ix_account_trade_underlying_symbol', 'account_trade', ['underlying_symbol'], unique=False)
    op.create_index('ix_account_trade_trade_type', 'account_trade', ['trade_type'], unique=False)
    op.create_index('ix_account_trade_trade_date', 'account_trade', ['trade_date'], unique=False)
    op.create_index('ix_account_trade_symbol', 'account_trade', ['symbol'], unique=False)
    op.create_index('ix_account_trade_expiry', 'account_trade', ['expiry'], unique=False)
    op.create_index('ix_account_trade_currency', 'account_trade', ['currency'], unique=False)
    op.create_index('ix_account_trade_commission_currency', 'account_trade', ['commission_currency'], unique=False)
    op.create_index('ix_account_trade_brokerage_id', 'account_trade', ['brokerage_id'], unique=False)
    op.create_index('ix_account_trade_asset_class', 'account_trade', ['asset_class'], unique=False)
    op.create_table('currency_bar_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('bar_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bar_open', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_high', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_low', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_close', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bar_volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bar_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('bar_size', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_currency_bar_data')
    )
    op.create_index('ix_currency_bar_data_symbol', 'currency_bar_data', ['symbol'], unique=False)
    op.create_index('ix_currency_bar_data_bar_date', 'currency_bar_data', ['bar_date'], unique=False)
    op.create_table('company_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_summary_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_summary')
    )
    op.create_index('ix_company_summary_company_id', 'company_summary', ['company_id'], unique=False)
    # ### end Alembic commands ###
