"""removed locked columns

Revision ID: 097aa9b87fe4
Revises: c2d8dab4326c
Create Date: 2022-10-10 11:13:41.554379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097aa9b87fe4'
down_revision = 'c2d8dab4326c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'locked')
    op.drop_column('currency_bar_data', 'locked')
    op.drop_column('equity_bar_data', 'locked')
    op.drop_column('industry', 'locked')
    op.drop_column('sector', 'locked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sector', sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('industry', sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('equity_bar_data', sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('currency_bar_data', sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
