"""rework tables

Revision ID: 28c1b60ddc31
Revises: 1140690fb442
Create Date: 2022-05-15 18:53:08.761899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c1b60ddc31'
down_revision = '1140690fb442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_industry_id', table_name='company')
    op.drop_constraint('fk_company_industry_id_industry', 'company', type_='foreignkey')
    op.drop_column('company', 'industry_id')
    op.add_column('company_group', sa.Column('industry_id', sa.SmallInteger(), nullable=False))
    op.create_index(op.f('ix_company_group_industry_id'), 'company_group', ['industry_id'], unique=False)
    op.create_foreign_key(op.f('fk_company_group_industry_id_industry'), 'company_group', 'industry', ['industry_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('company_group_relation', sa.Column('company_business_or_product_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_company_group_relation_company_id_company', 'company_group_relation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_group_relation_company_business_or_product_id_company_business_or_product'), 'company_group_relation', 'company_business_or_product', ['company_business_or_product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_group_relation', 'company_id')
    op.add_column('company_metric', sa.Column('company_metric_relation_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_company_metric_company_metric_relation_id'), 'company_metric', ['company_metric_relation_id'], unique=False)
    op.drop_index('ix_company_metric_company_metric_description_id', table_name='company_metric')
    op.drop_constraint('fk_company_metric_company_metric_description_id_company_befe', 'company_metric', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_metric_company_metric_relation_id_company_metric_relation'), 'company_metric', 'company_metric_relation', ['company_metric_relation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_metric', 'company_metric_description_id')
    op.drop_column('company_metric', 'look_back')
    op.add_column('company_metric_description', sa.Column('look_back', sa.Boolean(), nullable=False))
    op.add_column('company_metric_description', sa.Column('metric_duration', sa.SmallInteger(), nullable=False))
    op.add_column('company_metric_description', sa.Column('metric_duration_type', sa.SmallInteger(), nullable=False))
    op.create_index(op.f('ix_company_metric_description_code'), 'company_metric_description', ['code'], unique=False)
    op.create_index(op.f('ix_company_metric_description_look_back'), 'company_metric_description', ['look_back'], unique=False)
    op.create_index(op.f('ix_company_metric_description_metric_data_type'), 'company_metric_description', ['metric_data_type'], unique=False)
    op.create_index(op.f('ix_company_metric_description_metric_duration'), 'company_metric_description', ['metric_duration'], unique=False)
    op.create_index(op.f('ix_company_metric_description_metric_duration_type'), 'company_metric_description', ['metric_duration_type'], unique=False)
    op.create_unique_constraint(op.f('uq_company_metric_description_code'), 'company_metric_description', ['code', 'metric_data_type', 'metric_duration', 'metric_duration_type', 'look_back'])
    op.add_column('company_metric_description_note', sa.Column('company_metric_relation_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_company_metric_description_note_company_metric_relation_id'), 'company_metric_description_note', ['company_metric_relation_id'], unique=False)
    op.create_foreign_key(op.f('fk_company_metric_description_note_company_metric_relation_id_company_metric_relation'), 'company_metric_description_note', 'company_metric_relation', ['company_metric_relation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('company_metric_relation', sa.Column('company_group_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_company_metric_relation_company_metric_description_id', 'company_metric_relation', type_='unique')
    op.create_unique_constraint(op.f('uq_company_metric_relation_company_metric_description_id'), 'company_metric_relation', ['company_metric_description_id', 'company_group_id'])
    op.drop_constraint('fk_company_metric_relation_company_metric_description_n_bec4', 'company_metric_relation', type_='foreignkey')
    op.drop_constraint('fk_company_metric_relation_company_id_company', 'company_metric_relation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_metric_relation_company_group_id_company_group'), 'company_metric_relation', 'company_group', ['company_group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_metric_relation', 'company_id')
    op.drop_column('company_metric_relation', 'company_metric_description_note_id')
    op.add_column('company_sector_relation', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_company_sector_relation_company_id_company', 'company_sector_relation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_sector_relation_group_id_company_group'), 'company_sector_relation', 'company_group', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_sector_relation', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_sector_relation', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_sector_relation_group_id_company_group'), 'company_sector_relation', type_='foreignkey')
    op.create_foreign_key('fk_company_sector_relation_company_id_company', 'company_sector_relation', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_sector_relation', 'group_id')
    op.add_column('company_metric_relation', sa.Column('company_metric_description_note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('company_metric_relation', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_company_metric_relation_company_group_id_company_group'), 'company_metric_relation', type_='foreignkey')
    op.create_foreign_key('fk_company_metric_relation_company_id_company', 'company_metric_relation', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_company_metric_relation_company_metric_description_n_bec4', 'company_metric_relation', 'company_metric_description_note', ['company_metric_description_note_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('uq_company_metric_relation_company_metric_description_id'), 'company_metric_relation', type_='unique')
    op.create_unique_constraint('uq_company_metric_relation_company_metric_description_id', 'company_metric_relation', ['company_metric_description_id', 'company_metric_description_note_id', 'company_id'])
    op.drop_column('company_metric_relation', 'company_group_id')
    op.drop_constraint(op.f('fk_company_metric_description_note_company_metric_relation_id_company_metric_relation'), 'company_metric_description_note', type_='foreignkey')
    op.drop_index(op.f('ix_company_metric_description_note_company_metric_relation_id'), table_name='company_metric_description_note')
    op.drop_column('company_metric_description_note', 'company_metric_relation_id')
    op.drop_constraint(op.f('uq_company_metric_description_code'), 'company_metric_description', type_='unique')
    op.drop_index(op.f('ix_company_metric_description_metric_duration_type'), table_name='company_metric_description')
    op.drop_index(op.f('ix_company_metric_description_metric_duration'), table_name='company_metric_description')
    op.drop_index(op.f('ix_company_metric_description_metric_data_type'), table_name='company_metric_description')
    op.drop_index(op.f('ix_company_metric_description_look_back'), table_name='company_metric_description')
    op.drop_index(op.f('ix_company_metric_description_code'), table_name='company_metric_description')
    op.drop_column('company_metric_description', 'metric_duration_type')
    op.drop_column('company_metric_description', 'metric_duration')
    op.drop_column('company_metric_description', 'look_back')
    op.add_column('company_metric', sa.Column('look_back', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('company_metric', sa.Column('company_metric_description_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_metric_company_metric_relation_id_company_metric_relation'), 'company_metric', type_='foreignkey')
    op.create_foreign_key('fk_company_metric_company_metric_description_id_company_befe', 'company_metric', 'company_metric_description', ['company_metric_description_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_metric_company_metric_description_id', 'company_metric', ['company_metric_description_id'], unique=False)
    op.drop_index(op.f('ix_company_metric_company_metric_relation_id'), table_name='company_metric')
    op.drop_column('company_metric', 'company_metric_relation_id')
    op.add_column('company_group_relation', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_group_relation_company_business_or_product_id_company_business_or_product'), 'company_group_relation', type_='foreignkey')
    op.create_foreign_key('fk_company_group_relation_company_id_company', 'company_group_relation', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_group_relation', 'company_business_or_product_id')
    op.drop_constraint(op.f('fk_company_group_industry_id_industry'), 'company_group', type_='foreignkey')
    op.drop_index(op.f('ix_company_group_industry_id'), table_name='company_group')
    op.drop_column('company_group', 'industry_id')
    op.add_column('company', sa.Column('industry_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_company_industry_id_industry', 'company', 'industry', ['industry_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_industry_id', 'company', ['industry_id'], unique=False)
    # ### end Alembic commands ###
