"""added user_id column to metric_data tbl

Revision ID: cdfc13f1f06c
Revises: a618153e3aa0
Create Date: 2022-10-08 20:54:51.310390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfc13f1f06c'
down_revision = 'a618153e3aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_data', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_metric_data_user_id'), 'metric_data', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_metric_data_user_id_account'), 'metric_data', 'account', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_metric_data_user_id_account'), 'metric_data', type_='foreignkey')
    op.drop_index(op.f('ix_metric_data_user_id'), table_name='metric_data')
    op.drop_column('metric_data', 'user_id')
    # ### end Alembic commands ###
