"""set nullable desc

Revision ID: ad10c7af3bdd
Revises: 4eecf5347c8a
Create Date: 2022-05-15 19:18:55.686431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad10c7af3bdd'
down_revision = '4eecf5347c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_group', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_group', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
