"""added uq constraint financial data table

Revision ID: 5bf43a9fe9c5
Revises: 880cdfda0cd2
Create Date: 2022-05-16 23:24:44.607581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf43a9fe9c5'
down_revision = '880cdfda0cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_company_financial_data_company_id'), 'company_financial_data', ['company_id', 'data_type', 'calendar_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_company_financial_data_company_id'), 'company_financial_data', type_='unique')
    # ### end Alembic commands ###
