"""big db refactor

Revision ID: 5d0e7759303b
Revises: 526b4a0617b0
Create Date: 2022-09-24 11:42:01.081118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d0e7759303b'
down_revision = '526b4a0617b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_business_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_business_segment_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_business_segment'))
    )
    op.create_index(op.f('ix_company_business_segment_company_id'), 'company_business_segment', ['company_id'], unique=False)
    op.create_table('metric_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['account.id'], name=op.f('fk_metric_classification_creator_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_classification'))
    )
    op.create_table('screener_preset',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['account.id'], name=op.f('fk_screener_preset_creator_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screener_preset'))
    )
    op.create_table('company_exchange',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_exchange_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name=op.f('fk_company_exchange_exchange_id_exchange'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'exchange_id', name=op.f('pk_company_exchange'))
    )
    op.create_table('company_in_group',
    sa.Column('company_business_segment_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_business_segment_id'], ['company_business_segment.id'], name=op.f('fk_company_in_group_company_business_segment_id_company_business_segment'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['company_group.id'], name=op.f('fk_company_in_group_group_id_company_group'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_business_segment_id', 'group_id', name=op.f('pk_company_in_group'))
    )
    op.create_table('company_industry_relation',
    sa.Column('company_business_segment_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_business_segment_id'], ['company_business_segment.id'], name=op.f('fk_company_industry_relation_company_business_segment_id_company_business_segment'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], name=op.f('fk_company_industry_relation_industry_id_industry'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_business_segment_id', 'industry_id', name=op.f('pk_company_industry_relation'))
    )
    op.create_table('metric_description',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('metric_data_type', sa.SmallInteger(), nullable=False),
    sa.Column('metric_duration_type', sa.SmallInteger(), nullable=False),
    sa.Column('year_recorded', sa.SmallInteger(), nullable=False),
    sa.Column('quarter_recorded', sa.SmallInteger(), nullable=False),
    sa.Column('metric_duration', sa.SmallInteger(), nullable=False),
    sa.Column('look_back', sa.Boolean(), nullable=False),
    sa.Column('metric_fixed_year', sa.SmallInteger(), nullable=False),
    sa.Column('metric_fixed_quarter', sa.SmallInteger(), nullable=False),
    sa.Column('metric_classification_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['account.id'], name=op.f('fk_metric_description_creator_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_classification_id'], ['metric_classification.id'], name=op.f('fk_metric_description_metric_classification_id_metric_classification'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_description')),
    sa.UniqueConstraint('code', 'metric_data_type', 'metric_duration', 'metric_duration_type', 'look_back', 'metric_fixed_year', 'metric_fixed_quarter', name=op.f('uq_metric_description_code'))
    )
    op.create_index(op.f('ix_metric_description_code'), 'metric_description', ['code'], unique=False)
    op.create_index(op.f('ix_metric_description_look_back'), 'metric_description', ['look_back'], unique=False)
    op.create_index(op.f('ix_metric_description_metric_data_type'), 'metric_description', ['metric_data_type'], unique=False)
    op.create_index(op.f('ix_metric_description_metric_duration'), 'metric_description', ['metric_duration'], unique=False)
    op.create_index(op.f('ix_metric_description_metric_duration_type'), 'metric_description', ['metric_duration_type'], unique=False)
    op.create_index(op.f('ix_metric_description_metric_fixed_quarter'), 'metric_description', ['metric_fixed_quarter'], unique=False)
    op.create_index(op.f('ix_metric_description_metric_fixed_year'), 'metric_description', ['metric_fixed_year'], unique=False)
    op.create_index(op.f('ix_metric_description_quarter_recorded'), 'metric_description', ['quarter_recorded'], unique=False)
    op.create_index(op.f('ix_metric_description_year_recorded'), 'metric_description', ['year_recorded'], unique=False)
    op.create_table('user_company_group',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_user_company_group_account_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['company_group.id'], name=op.f('fk_user_company_group_group_id_company_group'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'group_id', name=op.f('pk_user_company_group'))
    )
    op.create_table('user_metric_classification',
    sa.Column('metric_classification_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_user_metric_classification_account_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_classification_id'], ['metric_classification.id'], name=op.f('fk_user_metric_classification_metric_classification_id_metric_classification'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_classification_id', 'account_id', name=op.f('pk_user_metric_classification'))
    )
    op.create_table('user_screener_preset',
    sa.Column('screener_preset_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_user_screener_preset_account_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screener_preset_id'], ['screener_preset.id'], name=op.f('fk_user_screener_preset_screener_preset_id_screener_preset'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('screener_preset_id', 'account_id', name=op.f('pk_user_screener_preset'))
    )
    op.create_table('company_group_metric_description',
    sa.Column('metric_description_id', sa.BigInteger(), nullable=False),
    sa.Column('company_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_group_id'], ['company_group.id'], name=op.f('fk_company_group_metric_description_company_group_id_company_group'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_description_id'], ['metric_description.id'], name=op.f('fk_company_group_metric_description_metric_description_id_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_description_id', 'company_group_id', name=op.f('pk_company_group_metric_description'))
    )
    op.create_table('metric_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('metric_description_id', sa.BigInteger(), nullable=False),
    sa.Column('company_business_segment_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['company_business_segment_id'], ['company_business_segment.id'], name=op.f('fk_metric_data_company_business_segment_id_company_business_segment'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_description_id'], ['metric_description.id'], name=op.f('fk_metric_data_metric_description_id_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_data'))
    )
    op.create_index(op.f('ix_metric_data_company_business_segment_id'), 'metric_data', ['company_business_segment_id'], unique=False)
    op.create_index(op.f('ix_metric_data_metric_description_id'), 'metric_data', ['metric_description_id'], unique=False)
    op.create_table('screener_preset_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('metric_description_id', sa.BigInteger(), nullable=False),
    sa.Column('screener_preset_id', sa.BigInteger(), nullable=False),
    sa.Column('data_numeric', sa.Numeric(), nullable=True),
    sa.Column('data_str', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['metric_description_id'], ['metric_description.id'], name=op.f('fk_screener_preset_data_metric_description_id_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screener_preset_id'], ['screener_preset.id'], name=op.f('fk_screener_preset_data_screener_preset_id_screener_preset'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screener_preset_data')),
    sa.UniqueConstraint('metric_description_id', 'screener_preset_id', name=op.f('uq_screener_preset_data_metric_description_id'))
    )
    op.create_table('user_metric_description',
    sa.Column('metric_description_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_user_metric_description_account_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_description_id'], ['metric_description.id'], name=op.f('fk_user_metric_description_metric_description_id_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_description_id', 'account_id', name=op.f('pk_user_metric_description'))
    )
    op.drop_index('ix_company_metric_company_business_or_product_id', table_name='company_metric')
    op.drop_index('ix_company_metric_company_metric_relation_id', table_name='company_metric')
    op.drop_table('company_metric')
    op.drop_index('ix_company_metric_description_code', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_look_back', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_metric_data_type', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_metric_duration', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_metric_duration_type', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_metric_fixed_quarter', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_metric_fixed_year', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_quarter_recorded', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_update_stamp', table_name='company_metric_description')
    op.drop_index('ix_company_metric_description_year_recorded', table_name='company_metric_description')
    op.drop_table('company_metrics_preset_relation')
    op.drop_table('company_metric_description_account_relation')
    op.drop_table('company_group_relation')
    op.drop_index('ix_company_metric_description_note_company_metric_relation_id', table_name='company_metric_description_note')
    op.drop_index('ix_company_metric_description_note_update_stamp', table_name='company_metric_description_note')
    op.drop_table('company_metric_description_note')
    op.drop_table('company_metric_relation')
    op.drop_table('company_exchange_relation')
    op.drop_table('company_metric_classification_account_relation')
    op.drop_index('ix_company_business_or_product_company_id', table_name='company_business_or_product')
    op.drop_table('company_metrics_preset')
    op.drop_table('company_metric_description')
    op.drop_table('company_metric_classification')
    op.drop_column('company', 'update_stamp')
    op.add_column('company_development', sa.Column('company_business_segment_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_company_development_company_business_segment_id'), 'company_development', ['company_business_segment_id'], unique=False)
    op.drop_index('ix_company_development_company_business_or_product', table_name='company_development')
    op.drop_constraint('fk_company_development_company_business_or_product_comp_09d7', 'company_development', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_development_company_business_segment_id_company_business_segment'), 'company_development', 'company_business_segment', ['company_business_segment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_development', 'company_business_or_product')
    op.add_column('company_group', sa.Column('creator_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('uq_company_group_name_code', 'company_group', type_='unique')
    op.create_unique_constraint(op.f('uq_company_group_name_code'), 'company_group', ['name_code', 'name', 'creator_id'])
    op.drop_index('ix_company_group_industry_id', table_name='company_group')
    op.drop_constraint('uq_company_group_name', 'company_group', type_='unique')
    op.drop_constraint('fk_company_group_industry_id_industry', 'company_group', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_group_creator_id_account'), 'company_group', 'account', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_group', 'industry_id')
    op.drop_column('company_group', 'update_stamp')
    op.add_column('company_sector_relation', sa.Column('company_business_segment_id', sa.Integer(), nullable=False))
    op.alter_column('company_sector_relation', 'sector_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer())
    op.drop_constraint('fk_company_sector_relation_group_id_company_group', 'company_sector_relation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_company_sector_relation_company_business_segment_id_company_business_segment'), 'company_sector_relation', 'company_business_segment', ['company_business_segment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('company_sector_relation', 'group_id')
    op.drop_column('company_sector_relation', 'update_stamp')
    op.drop_index('ix_company_summary_update_stamp', table_name='company_summary')
    op.drop_column('company_summary', 'update_stamp')
    op.drop_column('country_info', 'update_stamp')
    op.alter_column('equity_bar_data', 'exchange_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('exchange', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('exchange_id_seq'::regclass)"))
    op.drop_column('exchange', 'update_stamp')
    op.alter_column('industry', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('industry_id_seq'::regclass)"))
    op.alter_column('industry', 'sector_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('industry', 'update_stamp')
    op.drop_column('log', 'update_stamp')
    op.alter_column('sector', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('sector_id_seq'::regclass)"))
    op.drop_column('sector', 'update_stamp')
    # ### end Alembic commands ###

    op.drop_table('company_business_or_product')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sector', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('sector', 'id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('sector_id_seq'::regclass)"))
    op.add_column('log', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('industry', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('industry', 'sector_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('industry', 'id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('industry_id_seq'::regclass)"))
    op.add_column('exchange', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('exchange', 'id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('exchange_id_seq'::regclass)"))
    op.alter_column('equity_bar_data', 'exchange_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.add_column('country_info', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('company_summary', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index('ix_company_summary_update_stamp', 'company_summary', ['update_stamp'], unique=False)
    op.add_column('company_sector_relation', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('company_sector_relation', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_sector_relation_company_business_segment_id_company_business_segment'), 'company_sector_relation', type_='foreignkey')
    op.create_foreign_key('fk_company_sector_relation_group_id_company_group', 'company_sector_relation', 'company_group', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('company_sector_relation', 'sector_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT())
    op.drop_column('company_sector_relation', 'company_business_segment_id')
    op.add_column('company_group', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('company_group', sa.Column('industry_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_company_group_creator_id_account'), 'company_group', type_='foreignkey')
    op.create_foreign_key('fk_company_group_industry_id_industry', 'company_group', 'industry', ['industry_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('uq_company_group_name', 'company_group', ['name'])
    op.create_index('ix_company_group_industry_id', 'company_group', ['industry_id'], unique=False)
    op.drop_constraint(op.f('uq_company_group_name_code'), 'company_group', type_='unique')
    op.create_unique_constraint('uq_company_group_name_code', 'company_group', ['name_code'])
    op.drop_column('company_group', 'creator_id')
    op.add_column('company_development', sa.Column('company_business_or_product', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_company_development_company_business_segment_id_company_business_segment'), 'company_development', type_='foreignkey')
    op.create_foreign_key('fk_company_development_company_business_or_product_comp_09d7', 'company_development', 'company_business_or_product', ['company_business_or_product'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_company_development_company_business_or_product', 'company_development', ['company_business_or_product'], unique=False)
    op.drop_index(op.f('ix_company_development_company_business_segment_id'), table_name='company_development')
    op.drop_column('company_development', 'company_business_segment_id')
    op.add_column('company', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_table('company_metrics_preset',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('company_metrics_preset_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='fk_company_metrics_preset_account_id_account', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metrics_preset'),
    postgresql_ignore_search_path=False
    )
    op.create_table('company_metric_classification',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('company_metric_classification_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('parent_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['account.id'], name='fk_company_metric_classification_creator_id_account', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metric_classification'),
    postgresql_ignore_search_path=False
    )
    op.create_table('company_business_or_product',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('company_business_or_product_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_business_or_product_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_business_or_product'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_company_business_or_product_company_id', 'company_business_or_product', ['company_id'], unique=False)
    op.create_table('company_metric_classification_account_relation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_metric_classification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='fk_company_metric_classification_account_relation_accou_1507', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_classification_id'], ['company_metric_classification.id'], name='fk_company_metric_classification_account_relation_compa_d6cd', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metric_classification_account_relation'),
    sa.UniqueConstraint('company_metric_classification_id', 'account_id', name='uq_company_metric_classification_account_relation_compa_4feb')
    )
    op.create_table('company_exchange_relation',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_exchange_relation_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name='fk_company_exchange_relation_exchange_id_exchange', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'exchange_id', name='pk_company_exchange_relation')
    )
    op.create_table('company_metric_relation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('company_metric_relation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('company_metric_description_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_group_id'], ['company_group.id'], name='fk_company_metric_relation_company_group_id_company_group', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name='fk_company_metric_relation_company_metric_description_i_982e', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metric_relation'),
    sa.UniqueConstraint('company_metric_description_id', 'company_group_id', name='uq_company_metric_relation_company_metric_description_id'),
    postgresql_ignore_search_path=False
    )
    op.create_table('company_metric_description_note',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('note_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('company_metric_relation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_metric_relation_id'], ['company_metric_relation.id'], name='fk_company_metric_description_note_company_metric_relat_6856', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metric_description_note')
    )
    op.create_index('ix_company_metric_description_note_update_stamp', 'company_metric_description_note', ['update_stamp'], unique=False)
    op.create_index('ix_company_metric_description_note_company_metric_relation_id', 'company_metric_description_note', ['company_metric_relation_id'], unique=False)
    op.create_table('company_group_relation',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('company_business_or_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_business_or_product_id'], ['company_business_or_product.id'], name='fk_company_group_relation_company_business_or_product_i_3f23', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['company_group.id'], name='fk_company_group_relation_group_id_company_group', onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_table('company_metric_description_account_relation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_metric_description_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='fk_company_metric_description_account_relation_account__d227', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name='fk_company_metric_description_account_relation_company__671e', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metric_description_account_relation'),
    sa.UniqueConstraint('company_metric_description_id', 'account_id', name='uq_company_metric_description_account_relation_company__ec6a')
    )
    op.create_table('company_metrics_preset_relation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_metric_description_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_metric_preset_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('data_numeric', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('data_str', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name='fk_company_metrics_preset_relation_company_metric_descr_9488', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_preset_id'], ['company_metrics_preset.id'], name='fk_company_metrics_preset_relation_company_metric_prese_356d', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metrics_preset_relation'),
    sa.UniqueConstraint('company_metric_description_id', 'company_metric_preset_id', name='uq_company_metrics_preset_relation_company_metric_descr_4d8c')
    )
    op.create_table('company_metric_description',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('company_metric_description_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('metric_data_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('look_back', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('metric_duration', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('metric_duration_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('metric_fixed_quarter', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('metric_fixed_year', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('quarter_recorded', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('year_recorded', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('company_metric_classification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_metric_classification_id'], ['company_metric_classification.id'], name='fk_company_metric_description_company_metric_classifica_244b', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['account.id'], name='fk_company_metric_description_creator_id_account', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metric_description'),
    sa.UniqueConstraint('code', 'metric_data_type', 'metric_duration', 'metric_duration_type', 'look_back', 'metric_fixed_year', 'metric_fixed_quarter', name='uq_company_metric_description_code'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_company_metric_description_year_recorded', 'company_metric_description', ['year_recorded'], unique=False)
    op.create_index('ix_company_metric_description_update_stamp', 'company_metric_description', ['update_stamp'], unique=False)
    op.create_index('ix_company_metric_description_quarter_recorded', 'company_metric_description', ['quarter_recorded'], unique=False)
    op.create_index('ix_company_metric_description_metric_fixed_year', 'company_metric_description', ['metric_fixed_year'], unique=False)
    op.create_index('ix_company_metric_description_metric_fixed_quarter', 'company_metric_description', ['metric_fixed_quarter'], unique=False)
    op.create_index('ix_company_metric_description_metric_duration_type', 'company_metric_description', ['metric_duration_type'], unique=False)
    op.create_index('ix_company_metric_description_metric_duration', 'company_metric_description', ['metric_duration'], unique=False)
    op.create_index('ix_company_metric_description_metric_data_type', 'company_metric_description', ['metric_data_type'], unique=False)
    op.create_index('ix_company_metric_description_look_back', 'company_metric_description', ['look_back'], unique=False)
    op.create_index('ix_company_metric_description_code', 'company_metric_description', ['code'], unique=False)
    op.create_table('company_metric',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('company_business_or_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_metric_relation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_business_or_product_id'], ['company_business_or_product.id'], name='fk_company_metric_company_business_or_product_id_compan_ead7', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_relation_id'], ['company_metric_relation.id'], name='fk_company_metric_company_metric_relation_id_company_me_24c1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_company_metric')
    )
    op.create_index('ix_company_metric_company_metric_relation_id', 'company_metric', ['company_metric_relation_id'], unique=False)
    op.create_index('ix_company_metric_company_business_or_product_id', 'company_metric', ['company_business_or_product_id'], unique=False)
    op.drop_table('user_metric_description')
    op.drop_table('screener_preset_data')
    op.drop_index(op.f('ix_metric_data_metric_description_id'), table_name='metric_data')
    op.drop_index(op.f('ix_metric_data_company_business_segment_id'), table_name='metric_data')
    op.drop_table('metric_data')
    op.drop_table('company_group_metric_description')
    op.drop_table('user_screener_preset')
    op.drop_table('user_metric_classification')
    op.drop_table('user_company_group')
    op.drop_index(op.f('ix_metric_description_year_recorded'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_quarter_recorded'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_metric_fixed_year'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_metric_fixed_quarter'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_metric_duration_type'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_metric_duration'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_metric_data_type'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_look_back'), table_name='metric_description')
    op.drop_index(op.f('ix_metric_description_code'), table_name='metric_description')
    op.drop_table('metric_description')
    op.drop_table('company_industry_relation')
    op.drop_table('company_in_group')
    op.drop_table('company_exchange')
    op.drop_table('screener_preset')
    op.drop_table('metric_classification')
    op.drop_index(op.f('ix_company_business_segment_company_id'), table_name='company_business_segment')
    op.drop_table('company_business_segment')
    # ### end Alembic commands ###
