"""rename one table

Revision ID: 66347196da4f
Revises: 5d0e7759303b
Create Date: 2022-09-24 21:33:04.762166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66347196da4f'
down_revision = '5d0e7759303b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_exchange_relation',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_exchange_relation_company_id_company'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name=op.f('fk_company_exchange_relation_exchange_id_exchange'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'exchange_id', name=op.f('pk_company_exchange_relation'))
    )
    op.drop_table('company_exchange')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_exchange',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_company_exchange_company_id_company', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], name='fk_company_exchange_exchange_id_exchange', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'exchange_id', name='pk_company_exchange')
    )
    op.drop_table('company_exchange_relation')
    # ### end Alembic commands ###
