"""accunt + metric classification tableos

Revision ID: d0ba2dcdeb98
Revises: f2dcfc058ff0
Create Date: 2022-08-18 09:04:23.842471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0ba2dcdeb98'
down_revision = 'f2dcfc058ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('userName', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('email', name=op.f('uq_account_email')),
    sa.UniqueConstraint('password', name=op.f('uq_account_password')),
    sa.UniqueConstraint('phone', name=op.f('uq_account_phone')),
    sa.UniqueConstraint('userName', name=op.f('uq_account_userName'))
    )
    op.create_table('company_metric_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metric_classification'))
    )
    op.create_table('company_metric_classification_account_relation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_metric_classification_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_company_metric_classification_account_relation_account_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_classification_id'], ['company_metric_classification.id'], name=op.f('fk_company_metric_classification_account_relation_company_metric_classification_id_company_metric_classification'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metric_classification_account_relation')),
    sa.UniqueConstraint('company_metric_classification_id', 'account_id', name=op.f('uq_company_metric_classification_account_relation_company_metric_classification_id'))
    )
    op.create_table('company_metrics_preset',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_company_metrics_preset_account_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metrics_preset'))
    )
    op.create_table('company_metric_description_account_relation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_metric_description_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_company_metric_description_account_relation_account_id_account'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name=op.f('fk_company_metric_description_account_relation_company_metric_description_id_company_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metric_description_account_relation')),
    sa.UniqueConstraint('company_metric_description_id', 'account_id', name=op.f('uq_company_metric_description_account_relation_company_metric_description_id'))
    )
    op.create_table('company_metrics_preset_relation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_metric_description_id', sa.BigInteger(), nullable=False),
    sa.Column('company_metric_preset_id', sa.BigInteger(), nullable=False),
    sa.Column('data_numeric', sa.Numeric(), nullable=True),
    sa.Column('data_str', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['company_metric_description_id'], ['company_metric_description.id'], name=op.f('fk_company_metrics_preset_relation_company_metric_description_id_company_metric_description'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_metric_preset_id'], ['company_metrics_preset.id'], name=op.f('fk_company_metrics_preset_relation_company_metric_preset_id_company_metrics_preset'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_metrics_preset_relation')),
    sa.UniqueConstraint('company_metric_description_id', 'company_metric_preset_id', name=op.f('uq_company_metrics_preset_relation_company_metric_description_id'))
    )
    op.add_column('company_metric_description', sa.Column('company_metric_classification_id', sa.Integer(), nullable=False))
    op.alter_column('company_metric_description', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('company_metric_description_id_seq'::regclass)"))
    op.create_foreign_key(op.f('fk_company_metric_description_company_metric_classification_id_company_metric_classification'), 'company_metric_description', 'company_metric_classification', ['company_metric_classification_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('company_metric_relation', 'company_metric_description_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index('ix_company_metric_relation_update_stamp', table_name='company_metric_relation')
    op.drop_column('company_metric_relation', 'update_stamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metric_relation', sa.Column('update_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index('ix_company_metric_relation_update_stamp', 'company_metric_relation', ['update_stamp'], unique=False)
    op.alter_column('company_metric_relation', 'company_metric_description_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_company_metric_description_company_metric_classification_id_company_metric_classification'), 'company_metric_description', type_='foreignkey')
    op.alter_column('company_metric_description', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('company_metric_description_id_seq'::regclass)"))
    op.drop_column('company_metric_description', 'company_metric_classification_id')
    op.drop_table('company_metrics_preset_relation')
    op.drop_table('company_metric_description_account_relation')
    op.drop_table('company_metrics_preset')
    op.drop_table('company_metric_classification_account_relation')
    op.drop_table('company_metric_classification')
    op.drop_table('account')
    # ### end Alembic commands ###
