"""account pwd length

Revision ID: 526b4a0617b0
Revises: 0a6aa1674763
Create Date: 2022-09-02 11:06:06.080720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b4a0617b0'
down_revision = '0a6aa1674763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'password',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
