"""add description column to cpny group

Revision ID: 4eecf5347c8a
Revises: 7799e1790747
Create Date: 2022-05-15 19:08:29.718794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eecf5347c8a'
down_revision = '7799e1790747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_group', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_group', 'description')
    # ### end Alembic commands ###
