from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *
from sqlalchemy.schema import *

from db.base_models import Base, meta
from db.models import Company

class BalanceSheetData(Base):
    __tablename__ = 'balance_sheet_data'

    id = Column(Integer, primary_key=True)
    company_id = Column(ForeignKey('company.id', ondelete='CASCADE', onupdate='CASCADE'), nullable=False, index=True)
    assets = Column(BigInteger)
    cashneq = Column(BigInteger)
    investments = Column(BigInteger)
    investmentsc = Column(BigInteger)
    investmentsnc = Column(BigInteger)
    deferredrev = Column(BigInteger)
    deposits = Column(BigInteger)
    ppnenet = Column(BigInteger)
    inventory = Column(BigInteger)
    taxassets = Column(BigInteger)
    receivables = Column(BigInteger)
    payables = Column(BigInteger)
    intangibles = Column(BigInteger)
    liabilities = Column(BigInteger)
    equity = Column(BigInteger)
    retearn = Column(BigInteger)
    accoci = Column(BigInteger)
    assetsc = Column(BigInteger)
    assetsnc = Column(BigInteger)
    liabilitiesc = Column(BigInteger)
    liabilitiesnc = Column(BigInteger)
    taxliabilities = Column(BigInteger)
    debt = Column(BigInteger)
    debtc = Column(BigInteger)
    debtnc = Column(BigInteger)
    calendar_date = Column(DateTime(timezone=True), nullable=False, index=True)
    date_filed = Column(DateTime(timezone=True), nullable=False, index=True)
    locked = Column(Boolean, nullable=False, server_default=text("false"))
    update_stamp = Column(DateTime(timezone=True), nullable=False, server_default=FetchedValue())

class IncomeStatementData(Base):
    __tablename__ = 'income_statement_data'

    id = Column(Integer, primary_key=True)
    company_id = Column(ForeignKey('company.id', ondelete='CASCADE', onupdate='CASCADE'), nullable=False, index=True)
    revenue = Column(BigInteger)
    cor = Column(BigInteger)
    opex = Column(BigInteger)
    sgna = Column(BigInteger)
    rnd = Column(BigInteger)
    intexp = Column(BigInteger)
    taxexp = Column(BigInteger)
    netincdis = Column(BigInteger)   
    consolinc = Column(BigInteger)
    netincnci = Column(BigInteger)
    netinc = Column(BigInteger)
    prefdivis = Column(BigInteger)
    netinccmn = Column(BigInteger)
    shareswa = Column(BigInteger)
    shareswadil = Column(BigInteger)
    calendar_date = Column(DateTime(timezone=True), nullable=False, index=True)
    date_filed = Column(DateTime(timezone=True), nullable=False, index=True)
    locked = Column(Boolean, nullable=False, server_default=text("false"))
    update_stamp = Column(DateTime(timezone=True), nullable=False, server_default=FetchedValue())

class CashFlowStatementData(Base):
    __tablename__ = 'cash_flow_statement_data'

    id = Column(Integer, primary_key=True)
    company_id = Column(ForeignKey('company.id', ondelete='CASCADE', onupdate='CASCADE'), nullable=False, index=True)
    capex = Column(BigInteger)
    ncfbus = Column(BigInteger)
    ncfi = Column(BigInteger)
    ncfinv = Column(BigInteger)
    ncff = Column(BigInteger)
    ncfdebt = Column(BigInteger)
    ncfcommon = Column(BigInteger)
    ncfdiv = Column(BigInteger)
    ncfo = Column(BigInteger)  
    ncfx = Column(BigInteger)
    ncf = Column(BigInteger)
    sbcomp = Column(BigInteger)
    depamor = Column(BigInteger)
    calendar_date = Column(DateTime(timezone=True), nullable=False, index=True)
    date_filed = Column(DateTime(timezone=True), nullable=False, index=True)
    locked = Column(Boolean, nullable=False, server_default=text("false"))
    update_stamp = Column(DateTime(timezone=True), nullable=False, server_default=FetchedValue())

class CompanyFundamentalRatios(Base):
    __tablename__ = 'company_fundamental_ratios'

    id = Column(BigInteger, primary_key=True)
    company_id = Column(ForeignKey('company.id', ondelete='CASCADE', onupdate='CASCADE'), nullable=False, index=True)

    #liquidity ratios

    #current assets / current liabilities
    current_ratio_current = Column(Numeric, nullable=True)
    current_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    current_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    current_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    current_ratio_one_year_ago = Column(Numeric, nullable=True)
    current_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    current_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    current_ratio_three_years_ago = Column(Numeric, nullable=True)
    current_ratio_four_years_ago = Column(Numeric, nullable=True)
    current_ratio_five_years_ago = Column(Numeric, nullable=True)
    current_ratio_ten_years_ago = Column(Numeric, nullable=True)
    current_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    current_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    current_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    current_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    current_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    current_ratio_low = Column(Numeric, nullable=True)
    current_ratio_low_current_year = Column(Numeric, nullable=True)
    current_ratio_low_two_years = Column(Numeric, nullable=True)
    current_ratio_low_five_years = Column(Numeric, nullable=True)
    current_ratio_low_ten_years = Column(Numeric, nullable=True)
    current_ratio_low_twenty_years = Column(Numeric, nullable=True)
    current_ratio_high = Column(Numeric, nullable=True)
    current_ratio_high_current_year = Column(Numeric, nullable=True)
    current_ratio_high_two_years = Column(Numeric, nullable=True)
    current_ratio_high_five_years = Column(Numeric, nullable=True)
    current_ratio_high_ten_years = Column(Numeric, nullable=True)
    current_ratio_high_twenty_years = Column(Numeric, nullable=True)
    current_ratio_mean = Column(Numeric, nullable=True)
    current_ratio_mean_current_year = Column(Numeric, nullable=True)
    current_ratio_mean_two_years = Column(Numeric, nullable=True)
    current_ratio_mean_five_years = Column(Numeric, nullable=True)
    current_ratio_mean_ten_years = Column(Numeric, nullable=True)
    current_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    current_ratio_std_dev = Column(Numeric, nullable=True)
    current_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    current_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    current_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    current_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    current_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #(current assets - inventory) / current liabilities
    quick_ratio_current = Column(Numeric, nullable=True)
    quick_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    quick_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    quick_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    quick_ratio_one_year_ago = Column(Numeric, nullable=True)
    quick_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    quick_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    quick_ratio_three_years_ago = Column(Numeric, nullable=True)
    quick_ratio_four_years_ago = Column(Numeric, nullable=True)
    quick_ratio_five_years_ago = Column(Numeric, nullable=True)
    quick_ratio_ten_years_ago = Column(Numeric, nullable=True)
    quick_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    quick_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    quick_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    quick_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    quick_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    quick_ratio_low = Column(Numeric, nullable=True)
    quick_ratio_low_current_year = Column(Numeric, nullable=True)
    quick_ratio_low_two_years = Column(Numeric, nullable=True)
    quick_ratio_low_five_years = Column(Numeric, nullable=True)
    quick_ratio_low_ten_years = Column(Numeric, nullable=True)
    quick_ratio_low_twenty_years = Column(Numeric, nullable=True)
    quick_ratio_high = Column(Numeric, nullable=True)
    quick_ratio_high_current_year = Column(Numeric, nullable=True)
    quick_ratio_high_two_years = Column(Numeric, nullable=True)
    quick_ratio_high_five_years = Column(Numeric, nullable=True)
    quick_ratio_high_ten_years = Column(Numeric, nullable=True)
    quick_ratio_high_twenty_years = Column(Numeric, nullable=True)
    quick_ratio_mean = Column(Numeric, nullable=True)
    quick_ratio_mean_current_year = Column(Numeric, nullable=True)
    quick_ratio_mean_two_years = Column(Numeric, nullable=True)
    quick_ratio_mean_five_years = Column(Numeric, nullable=True)
    quick_ratio_mean_ten_years = Column(Numeric, nullable=True)
    quick_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    quick_ratio_std_dev = Column(Numeric, nullable=True)
    quick_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    quick_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    quick_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    quick_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    quick_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #cash & cash equivalents / current liabilities
    cash_ratio_current = Column(Numeric, nullable=True)
    cash_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    cash_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    cash_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    cash_ratio_one_year_ago = Column(Numeric, nullable=True)
    cash_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    cash_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    cash_ratio_three_years_ago = Column(Numeric, nullable=True)
    cash_ratio_four_years_ago = Column(Numeric, nullable=True)
    cash_ratio_five_years_ago = Column(Numeric, nullable=True)
    cash_ratio_ten_years_ago = Column(Numeric, nullable=True)
    cash_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    cash_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    cash_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    cash_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    cash_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    cash_ratio_low = Column(Numeric, nullable=True)
    cash_ratio_low_current_year = Column(Numeric, nullable=True)
    cash_ratio_low_two_years = Column(Numeric, nullable=True)
    cash_ratio_low_five_years = Column(Numeric, nullable=True)
    cash_ratio_low_ten_years = Column(Numeric, nullable=True)
    cash_ratio_low_twenty_years = Column(Numeric, nullable=True)
    cash_ratio_high = Column(Numeric, nullable=True)
    cash_ratio_high_current_year = Column(Numeric, nullable=True)
    cash_ratio_high_two_years = Column(Numeric, nullable=True)
    cash_ratio_high_five_years = Column(Numeric, nullable=True)
    cash_ratio_high_ten_years = Column(Numeric, nullable=True)
    cash_ratio_high_twenty_years = Column(Numeric, nullable=True)
    cash_ratio_mean = Column(Numeric, nullable=True)
    cash_ratio_mean_current_year = Column(Numeric, nullable=True)
    cash_ratio_mean_two_years = Column(Numeric, nullable=True)
    cash_ratio_mean_five_years = Column(Numeric, nullable=True)
    cash_ratio_mean_ten_years = Column(Numeric, nullable=True)
    cash_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    cash_ratio_std_dev = Column(Numeric, nullable=True)
    cash_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    cash_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    cash_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    cash_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    cash_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #operating cash flow / current liabilities
    operating_cash_flow_ratio_current = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_one_year_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_three_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_four_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_five_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_ten_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_low = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_low_current_year = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_low_two_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_low_five_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_low_ten_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_low_twenty_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_high = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_high_current_year = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_high_two_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_high_five_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_high_ten_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_high_twenty_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_mean = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_mean_current_year = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_mean_two_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_mean_five_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_mean_ten_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_std_dev = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    operating_cash_flow_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)


    #leverage ratios

    #total debt / total assets
    debt_ratio_current = Column(Numeric, nullable=True)
    debt_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    debt_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    debt_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    debt_ratio_one_year_ago = Column(Numeric, nullable=True)
    debt_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    debt_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    debt_ratio_three_years_ago = Column(Numeric, nullable=True)
    debt_ratio_four_years_ago = Column(Numeric, nullable=True)
    debt_ratio_five_years_ago = Column(Numeric, nullable=True)
    debt_ratio_ten_years_ago = Column(Numeric, nullable=True)
    debt_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    debt_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    debt_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    debt_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    debt_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    debt_ratio_low = Column(Numeric, nullable=True)
    debt_ratio_low_current_year = Column(Numeric, nullable=True)
    debt_ratio_low_two_years = Column(Numeric, nullable=True)
    debt_ratio_low_five_years = Column(Numeric, nullable=True)
    debt_ratio_low_ten_years = Column(Numeric, nullable=True)
    debt_ratio_low_twenty_years = Column(Numeric, nullable=True)
    debt_ratio_high = Column(Numeric, nullable=True)
    debt_ratio_high_current_year = Column(Numeric, nullable=True)
    debt_ratio_high_two_years = Column(Numeric, nullable=True)
    debt_ratio_high_five_years = Column(Numeric, nullable=True)
    debt_ratio_high_ten_years = Column(Numeric, nullable=True)
    debt_ratio_high_twenty_years = Column(Numeric, nullable=True)
    debt_ratio_mean = Column(Numeric, nullable=True)
    debt_ratio_mean_current_year = Column(Numeric, nullable=True)
    debt_ratio_mean_two_years = Column(Numeric, nullable=True)
    debt_ratio_mean_five_years = Column(Numeric, nullable=True)
    debt_ratio_mean_ten_years = Column(Numeric, nullable=True)
    debt_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    debt_ratio_std_dev = Column(Numeric, nullable=True)
    debt_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    debt_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    debt_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    debt_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    debt_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)
    
    #total liabilities / total shareholder's equity
    debt_to_equity_ratio_current = Column(Numeric, nullable=True)
    debt_to_equity_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_one_year_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_three_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_four_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_five_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_ten_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    debt_to_equity_ratio_low = Column(Numeric, nullable=True)
    debt_to_equity_ratio_low_current_year = Column(Numeric, nullable=True)
    debt_to_equity_ratio_low_two_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_low_five_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_low_ten_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_low_twenty_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_high = Column(Numeric, nullable=True)
    debt_to_equity_ratio_high_current_year = Column(Numeric, nullable=True)
    debt_to_equity_ratio_high_two_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_high_five_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_high_ten_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_high_twenty_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_mean = Column(Numeric, nullable=True)
    debt_to_equity_ratio_mean_current_year = Column(Numeric, nullable=True)
    debt_to_equity_ratio_mean_two_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_mean_five_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_mean_ten_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_std_dev = Column(Numeric, nullable=True)
    debt_to_equity_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    debt_to_equity_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    debt_to_equity_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #total assets / shareholder's equity
    equity_multiplier_current = Column(Numeric, nullable=True)
    equity_multiplier_one_quarter_ago = Column(Numeric, nullable=True)
    equity_multiplier_two_quarters_ago = Column(Numeric, nullable=True)
    equity_multiplier_three_quarters_ago = Column(Numeric, nullable=True)
    equity_multiplier_one_year_ago = Column(Numeric, nullable=True)
    equity_multiplier_one_year_half_ago = Column(Numeric, nullable=True)
    equity_multiplier_two_years_ago_ago = Column(Numeric, nullable=True)
    equity_multiplier_three_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_four_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_five_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_ten_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_fifteen_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_twenty_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_thirty_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_fourty_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_fifty_years_ago = Column(Numeric, nullable=True)
    equity_multiplier_low = Column(Numeric, nullable=True)
    equity_multiplier_low_current_year = Column(Numeric, nullable=True)
    equity_multiplier_low_two_years = Column(Numeric, nullable=True)
    equity_multiplier_low_five_years = Column(Numeric, nullable=True)
    equity_multiplier_low_ten_years = Column(Numeric, nullable=True)
    equity_multiplier_low_twenty_years = Column(Numeric, nullable=True)
    equity_multiplier_high = Column(Numeric, nullable=True)
    equity_multiplier_high_current_year = Column(Numeric, nullable=True)
    equity_multiplier_high_two_years = Column(Numeric, nullable=True)
    equity_multiplier_high_five_years = Column(Numeric, nullable=True)
    equity_multiplier_high_ten_years = Column(Numeric, nullable=True)
    equity_multiplier_high_twenty_years = Column(Numeric, nullable=True)
    equity_multiplier_mean = Column(Numeric, nullable=True)
    equity_multiplier_mean_current_year = Column(Numeric, nullable=True)
    equity_multiplier_mean_two_years = Column(Numeric, nullable=True)
    equity_multiplier_mean_five_years = Column(Numeric, nullable=True)
    equity_multiplier_mean_ten_years = Column(Numeric, nullable=True)
    equity_multiplier_mean_twenty_years = Column(Numeric, nullable=True)
    equity_multiplier_std_dev = Column(Numeric, nullable=True)
    equity_multiplier_std_dev_current_year = Column(Numeric, nullable=True)
    equity_multiplier_std_dev_two_years = Column(Numeric, nullable=True)
    equity_multiplier_std_dev_five_years = Column(Numeric, nullable=True)
    equity_multiplier_std_dev_ten_years = Column(Numeric, nullable=True)
    equity_multiplier_std_dev_twenty_years = Column(Numeric, nullable=True)

    #earnings before intest and taxes (EBIT) / interest expenses
    interest_coverage_ratio_current = Column(Numeric, nullable=True)
    interest_coverage_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_one_year_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_three_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_four_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_five_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_ten_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    interest_coverage_ratio_low = Column(Numeric, nullable=True)
    interest_coverage_ratio_low_current_year = Column(Numeric, nullable=True)
    interest_coverage_ratio_low_two_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_low_five_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_low_ten_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_low_twenty_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_high = Column(Numeric, nullable=True)
    interest_coverage_ratio_high_current_year = Column(Numeric, nullable=True)
    interest_coverage_ratio_high_two_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_high_five_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_high_ten_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_high_twenty_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_mean = Column(Numeric, nullable=True)
    interest_coverage_ratio_mean_current_year = Column(Numeric, nullable=True)
    interest_coverage_ratio_mean_two_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_mean_five_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_mean_ten_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_std_dev = Column(Numeric, nullable=True)
    interest_coverage_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    interest_coverage_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    interest_coverage_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    
    #net operating income / total debt service = (revenue - certain operating expenses) / current debt
    debt_service_coverage_ratio_current = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_one_year_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_three_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_four_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_five_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_ten_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_low = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_low_current_year = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_low_two_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_low_five_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_low_ten_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_low_twenty_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_high = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_high_current_year = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_high_two_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_high_five_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_high_ten_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_high_twenty_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_mean = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_mean_current_year = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_mean_two_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_mean_five_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_mean_ten_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_std_dev = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    debt_service_coverage_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #efficiency ratios

    #total sales ttm / ((assets start of period + assets end of period) / 2)
    asset_turnover_ratio_current = Column(Numeric, nullable=True)
    asset_turnover_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_one_year_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_three_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_four_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_five_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_ten_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    asset_turnover_ratio_low = Column(Numeric, nullable=True)
    asset_turnover_ratio_low_current_year = Column(Numeric, nullable=True)
    asset_turnover_ratio_low_two_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_low_five_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_low_ten_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_low_twenty_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_high = Column(Numeric, nullable=True)
    asset_turnover_ratio_high_current_year = Column(Numeric, nullable=True)
    asset_turnover_ratio_high_two_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_high_five_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_high_ten_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_high_twenty_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_mean = Column(Numeric, nullable=True)
    asset_turnover_ratio_mean_current_year = Column(Numeric, nullable=True)
    asset_turnover_ratio_mean_two_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_mean_five_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_mean_ten_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_std_dev = Column(Numeric, nullable=True)
    asset_turnover_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    asset_turnover_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    asset_turnover_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)
    
    #sales / average inventory = sales / ((beginning inventory + ending inventory) / 2)
    inventory_turnover_ratio_current = Column(Numeric, nullable=True)
    inventory_turnover_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_one_year_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_three_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_four_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_five_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_ten_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    inventory_turnover_ratio_low = Column(Numeric, nullable=True)
    inventory_turnover_ratio_low_current_year = Column(Numeric, nullable=True)
    inventory_turnover_ratio_low_two_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_low_five_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_low_ten_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_low_twenty_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_high = Column(Numeric, nullable=True)
    inventory_turnover_ratio_high_current_year = Column(Numeric, nullable=True)
    inventory_turnover_ratio_high_two_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_high_five_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_high_ten_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_high_twenty_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_mean = Column(Numeric, nullable=True)
    inventory_turnover_ratio_mean_current_year = Column(Numeric, nullable=True)
    inventory_turnover_ratio_mean_two_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_mean_five_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_mean_ten_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_std_dev = Column(Numeric, nullable=True)
    inventory_turnover_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    inventory_turnover_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    inventory_turnover_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #net credit sales / average accounts receivable
    acc_receivables_turnover_ratio_current = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_one_year_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_three_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_four_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_five_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_ten_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_low = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_low_current_year = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_low_two_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_low_five_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_low_ten_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_low_twenty_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_high = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_high_current_year = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_high_two_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_high_five_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_high_ten_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_high_twenty_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_mean = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_mean_current_year = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_mean_two_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_mean_five_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_mean_ten_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_std_dev = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    acc_receivables_turnover_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)


    #profitability ratios

    #net sales - cost of goods sold
    gross_margin_current = Column(Numeric, nullable=True)
    gross_margin_one_quarter_ago = Column(Numeric, nullable=True)
    gross_margin_two_quarters_ago = Column(Numeric, nullable=True)
    gross_margin_three_quarters_ago = Column(Numeric, nullable=True)
    gross_margin_one_year_ago = Column(Numeric, nullable=True)
    gross_margin_one_year_half_ago = Column(Numeric, nullable=True)
    gross_margin_two_years_ago_ago = Column(Numeric, nullable=True)
    gross_margin_three_years_ago = Column(Numeric, nullable=True)
    gross_margin_four_years_ago = Column(Numeric, nullable=True)
    gross_margin_five_years_ago = Column(Numeric, nullable=True)
    gross_margin_ten_years_ago = Column(Numeric, nullable=True)
    gross_margin_fifteen_years_ago = Column(Numeric, nullable=True)
    gross_margin_twenty_years_ago = Column(Numeric, nullable=True)
    gross_margin_thirty_years_ago = Column(Numeric, nullable=True)
    gross_margin_fourty_years_ago = Column(Numeric, nullable=True)
    gross_margin_fifty_years_ago = Column(Numeric, nullable=True)
    gross_margin_low = Column(Numeric, nullable=True)
    gross_margin_low_current_year = Column(Numeric, nullable=True)
    gross_margin_low_two_years = Column(Numeric, nullable=True)
    gross_margin_low_five_years = Column(Numeric, nullable=True)
    gross_margin_low_ten_years = Column(Numeric, nullable=True)
    gross_margin_low_twenty_years = Column(Numeric, nullable=True)
    gross_margin_high = Column(Numeric, nullable=True)
    gross_margin_high_current_year = Column(Numeric, nullable=True)
    gross_margin_high_two_years = Column(Numeric, nullable=True)
    gross_margin_high_five_years = Column(Numeric, nullable=True)
    gross_margin_high_ten_years = Column(Numeric, nullable=True)
    gross_margin_high_twenty_years = Column(Numeric, nullable=True)
    gross_margin_mean = Column(Numeric, nullable=True)
    gross_margin_mean_current_year = Column(Numeric, nullable=True)
    gross_margin_mean_two_years = Column(Numeric, nullable=True)
    gross_margin_mean_five_years = Column(Numeric, nullable=True)
    gross_margin_mean_ten_years = Column(Numeric, nullable=True)
    gross_margin_mean_twenty_years = Column(Numeric, nullable=True)
    gross_margin_std_dev = Column(Numeric, nullable=True)
    gross_margin_std_dev_current_year = Column(Numeric, nullable=True)
    gross_margin_std_dev_two_years = Column(Numeric, nullable=True)
    gross_margin_std_dev_five_years = Column(Numeric, nullable=True)
    gross_margin_std_dev_ten_years = Column(Numeric, nullable=True)
    gross_margin_std_dev_twenty_years = Column(Numeric, nullable=True)

    #operating income - revenue
    operating_margin_current = Column(Numeric, nullable=True)
    operating_margin_one_quarter_ago = Column(Numeric, nullable=True)
    operating_margin_two_quarters_ago = Column(Numeric, nullable=True)
    operating_margin_three_quarters_ago = Column(Numeric, nullable=True)
    operating_margin_one_year_ago = Column(Numeric, nullable=True)
    operating_margin_one_year_half_ago = Column(Numeric, nullable=True)
    operating_margin_two_years_ago_ago = Column(Numeric, nullable=True)
    operating_margin_three_years_ago = Column(Numeric, nullable=True)
    operating_margin_four_years_ago = Column(Numeric, nullable=True)
    operating_margin_five_years_ago = Column(Numeric, nullable=True)
    operating_margin_ten_years_ago = Column(Numeric, nullable=True)
    operating_margin_fifteen_years_ago = Column(Numeric, nullable=True)
    operating_margin_twenty_years_ago = Column(Numeric, nullable=True)
    operating_margin_thirty_years_ago = Column(Numeric, nullable=True)
    operating_margin_fourty_years_ago = Column(Numeric, nullable=True)
    operating_margin_fifty_years_ago = Column(Numeric, nullable=True)
    operating_margin_low = Column(Numeric, nullable=True)
    operating_margin_low_current_year = Column(Numeric, nullable=True)
    operating_margin_low_two_years = Column(Numeric, nullable=True)
    operating_margin_low_five_years = Column(Numeric, nullable=True)
    operating_margin_low_ten_years = Column(Numeric, nullable=True)
    operating_margin_low_twenty_years = Column(Numeric, nullable=True)
    operating_margin_high = Column(Numeric, nullable=True)
    operating_margin_high_current_year = Column(Numeric, nullable=True)
    operating_margin_high_two_years = Column(Numeric, nullable=True)
    operating_margin_high_five_years = Column(Numeric, nullable=True)
    operating_margin_high_ten_years = Column(Numeric, nullable=True)
    operating_margin_high_twenty_years = Column(Numeric, nullable=True)
    operating_margin_mean = Column(Numeric, nullable=True)
    operating_margin_mean_current_year = Column(Numeric, nullable=True)
    operating_margin_mean_two_years = Column(Numeric, nullable=True)
    operating_margin_mean_five_years = Column(Numeric, nullable=True)
    operating_margin_mean_ten_years = Column(Numeric, nullable=True)
    operating_margin_mean_twenty_years = Column(Numeric, nullable=True)
    operating_margin_std_dev = Column(Numeric, nullable=True)
    operating_margin_std_dev_current_year = Column(Numeric, nullable=True)
    operating_margin_std_dev_two_years = Column(Numeric, nullable=True)
    operating_margin_std_dev_five_years = Column(Numeric, nullable=True)
    operating_margin_std_dev_ten_years = Column(Numeric, nullable=True)
    operating_margin_std_dev_twenty_years = Column(Numeric, nullable=True)

    #net income / total assets
    return_on_assets_current = Column(Numeric, nullable=True)
    return_on_assets_one_quarter_ago = Column(Numeric, nullable=True)
    return_on_assets_two_quarters_ago = Column(Numeric, nullable=True)
    return_on_assets_three_quarters_ago = Column(Numeric, nullable=True)
    return_on_assets_one_year_ago = Column(Numeric, nullable=True)
    return_on_assets_one_year_half_ago = Column(Numeric, nullable=True)
    return_on_assets_two_years_ago_ago = Column(Numeric, nullable=True)
    return_on_assets_three_years_ago = Column(Numeric, nullable=True)
    return_on_assets_four_years_ago = Column(Numeric, nullable=True)
    return_on_assets_five_years_ago = Column(Numeric, nullable=True)
    return_on_assets_ten_years_ago = Column(Numeric, nullable=True)
    return_on_assets_fifteen_years_ago = Column(Numeric, nullable=True)
    return_on_assets_twenty_years_ago = Column(Numeric, nullable=True)
    return_on_assets_thirty_years_ago = Column(Numeric, nullable=True)
    return_on_assets_fourty_years_ago = Column(Numeric, nullable=True)
    return_on_assets_fifty_years_ago = Column(Numeric, nullable=True)
    return_on_assets_low = Column(Numeric, nullable=True)
    return_on_assets_low_current_year = Column(Numeric, nullable=True)
    return_on_assets_low_two_years = Column(Numeric, nullable=True)
    return_on_assets_low_five_years = Column(Numeric, nullable=True)
    return_on_assets_low_ten_years = Column(Numeric, nullable=True)
    return_on_assets_low_twenty_years = Column(Numeric, nullable=True)
    return_on_assets_high = Column(Numeric, nullable=True)
    return_on_assets_high_current_year = Column(Numeric, nullable=True)
    return_on_assets_high_two_years = Column(Numeric, nullable=True)
    return_on_assets_high_five_years = Column(Numeric, nullable=True)
    return_on_assets_high_ten_years = Column(Numeric, nullable=True)
    return_on_assets_high_twenty_years = Column(Numeric, nullable=True)
    return_on_assets_mean = Column(Numeric, nullable=True)
    return_on_assets_mean_current_year = Column(Numeric, nullable=True)
    return_on_assets_mean_two_years = Column(Numeric, nullable=True)
    return_on_assets_mean_five_years = Column(Numeric, nullable=True)
    return_on_assets_mean_ten_years = Column(Numeric, nullable=True)
    return_on_assets_mean_twenty_years = Column(Numeric, nullable=True)
    return_on_assets_std_dev = Column(Numeric, nullable=True)
    return_on_assets_std_dev_current_year = Column(Numeric, nullable=True)
    return_on_assets_std_dev_two_years = Column(Numeric, nullable=True)
    return_on_assets_std_dev_five_years = Column(Numeric, nullable=True)
    return_on_assets_std_dev_ten_years = Column(Numeric, nullable=True)
    return_on_assets_std_dev_twenty_years = Column(Numeric, nullable=True)

    #net income / shareholder's equity
    return_on_equity_current = Column(Numeric, nullable=True)
    return_on_equity_one_quarter_ago = Column(Numeric, nullable=True)
    return_on_equity_two_quarters_ago = Column(Numeric, nullable=True)
    return_on_equity_three_quarters_ago = Column(Numeric, nullable=True)
    return_on_equity_one_year_ago = Column(Numeric, nullable=True)
    return_on_equity_one_year_half_ago = Column(Numeric, nullable=True)
    return_on_equity_two_years_ago_ago = Column(Numeric, nullable=True)
    return_on_equity_three_years_ago = Column(Numeric, nullable=True)
    return_on_equity_four_years_ago = Column(Numeric, nullable=True)
    return_on_equity_five_years_ago = Column(Numeric, nullable=True)
    return_on_equity_ten_years_ago = Column(Numeric, nullable=True)
    return_on_equity_fifteen_years_ago = Column(Numeric, nullable=True)
    return_on_equity_twenty_years_ago = Column(Numeric, nullable=True)
    return_on_equity_thirty_years_ago = Column(Numeric, nullable=True)
    return_on_equity_fourty_years_ago = Column(Numeric, nullable=True)
    return_on_equity_fifty_years_ago = Column(Numeric, nullable=True)
    return_on_equity_low = Column(Numeric, nullable=True)
    return_on_equity_low_current_year = Column(Numeric, nullable=True)
    return_on_equity_low_two_years = Column(Numeric, nullable=True)
    return_on_equity_low_five_years = Column(Numeric, nullable=True)
    return_on_equity_low_ten_years = Column(Numeric, nullable=True)
    return_on_equity_low_twenty_years = Column(Numeric, nullable=True)
    return_on_equity_high = Column(Numeric, nullable=True)
    return_on_equity_high_current_year = Column(Numeric, nullable=True)
    return_on_equity_high_two_years = Column(Numeric, nullable=True)
    return_on_equity_high_five_years = Column(Numeric, nullable=True)
    return_on_equity_high_ten_years = Column(Numeric, nullable=True)
    return_on_equity_high_twenty_years = Column(Numeric, nullable=True)
    return_on_equity_mean = Column(Numeric, nullable=True)
    return_on_equity_mean_current_year = Column(Numeric, nullable=True)
    return_on_equity_mean_two_years = Column(Numeric, nullable=True)
    return_on_equity_mean_five_years = Column(Numeric, nullable=True)
    return_on_equity_mean_ten_years = Column(Numeric, nullable=True)
    return_on_equity_mean_twenty_years = Column(Numeric, nullable=True)
    return_on_equity_std_dev = Column(Numeric, nullable=True)
    return_on_equity_std_dev_current_year = Column(Numeric, nullable=True)
    return_on_equity_std_dev_two_years = Column(Numeric, nullable=True)
    return_on_equity_std_dev_five_years = Column(Numeric, nullable=True)
    return_on_equity_std_dev_ten_years = Column(Numeric, nullable=True)
    return_on_equity_std_dev_twenty_years = Column(Numeric, nullable=True)

    #shareholder ratios
    
    #net income available to shareholders / number of shares outstanding
    eps_current = Column(Numeric, nullable=True)
    eps_one_quarter_ago = Column(Numeric, nullable=True)
    eps_two_quarters_ago = Column(Numeric, nullable=True)
    eps_three_quarters_ago = Column(Numeric, nullable=True)
    eps_one_year_ago = Column(Numeric, nullable=True)
    eps_one_year_half_ago = Column(Numeric, nullable=True)
    eps_two_years_ago_ago = Column(Numeric, nullable=True)
    eps_three_years_ago = Column(Numeric, nullable=True)
    eps_four_years_ago = Column(Numeric, nullable=True)
    eps_five_years_ago = Column(Numeric, nullable=True)
    eps_ten_years_ago = Column(Numeric, nullable=True)
    eps_fifteen_years_ago = Column(Numeric, nullable=True)
    eps_twenty_years_ago = Column(Numeric, nullable=True)
    eps_thirty_years_ago = Column(Numeric, nullable=True)
    eps_fourty_years_ago = Column(Numeric, nullable=True)
    eps_fifty_years_ago = Column(Numeric, nullable=True)
    eps_low = Column(Numeric, nullable=True)
    eps_low_current_year = Column(Numeric, nullable=True)
    eps_low_two_years = Column(Numeric, nullable=True)
    eps_low_five_years = Column(Numeric, nullable=True)
    eps_low_ten_years = Column(Numeric, nullable=True)
    eps_low_twenty_years = Column(Numeric, nullable=True)
    eps_high = Column(Numeric, nullable=True)
    eps_high_current_year = Column(Numeric, nullable=True)
    eps_high_two_years = Column(Numeric, nullable=True)
    eps_high_five_years = Column(Numeric, nullable=True)
    eps_high_ten_years = Column(Numeric, nullable=True)
    eps_high_twenty_years = Column(Numeric, nullable=True)
    eps_mean = Column(Numeric, nullable=True)
    eps_mean_current_year = Column(Numeric, nullable=True)
    eps_mean_two_years = Column(Numeric, nullable=True)
    eps_mean_five_years = Column(Numeric, nullable=True)
    eps_mean_ten_years = Column(Numeric, nullable=True)
    eps_mean_twenty_years = Column(Numeric, nullable=True)
    eps_std_dev = Column(Numeric, nullable=True)
    eps_std_dev_current_year = Column(Numeric, nullable=True)
    eps_std_dev_two_years = Column(Numeric, nullable=True)
    eps_std_dev_five_years = Column(Numeric, nullable=True)
    eps_std_dev_ten_years = Column(Numeric, nullable=True)
    eps_std_dev_twenty_years = Column(Numeric, nullable=True)

    cfps_current = Column(Numeric, nullable=True)
    cfps_one_quarter_ago = Column(Numeric, nullable=True)
    cfps_two_quarters_ago = Column(Numeric, nullable=True)
    cfps_three_quarters_ago = Column(Numeric, nullable=True)
    cfps_one_year_ago = Column(Numeric, nullable=True)
    cfps_one_year_half_ago = Column(Numeric, nullable=True)
    cfps_two_years_ago_ago = Column(Numeric, nullable=True)
    cfps_three_years_ago = Column(Numeric, nullable=True)
    cfps_four_years_ago = Column(Numeric, nullable=True)
    cfps_five_years_ago = Column(Numeric, nullable=True)
    cfps_ten_years_ago = Column(Numeric, nullable=True)
    cfps_fifteen_years_ago = Column(Numeric, nullable=True)
    cfps_twenty_years_ago = Column(Numeric, nullable=True)
    cfps_thirty_years_ago = Column(Numeric, nullable=True)
    cfps_fourty_years_ago = Column(Numeric, nullable=True)
    cfps_fifty_years_ago = Column(Numeric, nullable=True)
    cfps_low = Column(Numeric, nullable=True)
    cfps_low_current_year = Column(Numeric, nullable=True)
    cfps_low_two_years = Column(Numeric, nullable=True)
    cfps_low_five_years = Column(Numeric, nullable=True)
    cfps_low_ten_years = Column(Numeric, nullable=True)
    cfps_low_twenty_years = Column(Numeric, nullable=True)
    cfps_high = Column(Numeric, nullable=True)
    cfps_high_current_year = Column(Numeric, nullable=True)
    cfps_high_two_years = Column(Numeric, nullable=True)
    cfps_high_five_years = Column(Numeric, nullable=True)
    cfps_high_ten_years = Column(Numeric, nullable=True)
    cfps_high_twenty_years = Column(Numeric, nullable=True)
    cfps_mean = Column(Numeric, nullable=True)
    cfps_mean_current_year = Column(Numeric, nullable=True)
    cfps_mean_two_years = Column(Numeric, nullable=True)
    cfps_mean_five_years = Column(Numeric, nullable=True)
    cfps_mean_ten_years = Column(Numeric, nullable=True)
    cfps_mean_twenty_years = Column(Numeric, nullable=True)
    cfps_std_dev = Column(Numeric, nullable=True)
    cfps_std_dev_current_year = Column(Numeric, nullable=True)
    cfps_std_dev_two_years = Column(Numeric, nullable=True)
    cfps_std_dev_five_years = Column(Numeric, nullable=True)
    cfps_std_dev_ten_years = Column(Numeric, nullable=True)
    cfps_std_dev_twenty_years = Column(Numeric, nullable=True)

    cps_current = Column(Numeric, nullable=True)
    cps_one_quarter_ago = Column(Numeric, nullable=True)
    cps_two_quarters_ago = Column(Numeric, nullable=True)
    cps_three_quarters_ago = Column(Numeric, nullable=True)
    cps_one_year_ago = Column(Numeric, nullable=True)
    cps_one_year_half_ago = Column(Numeric, nullable=True)
    cps_two_years_ago_ago = Column(Numeric, nullable=True)
    cps_three_years_ago = Column(Numeric, nullable=True)
    cps_four_years_ago = Column(Numeric, nullable=True)
    cps_five_years_ago = Column(Numeric, nullable=True)
    cps_ten_years_ago = Column(Numeric, nullable=True)
    cps_fifteen_years_ago = Column(Numeric, nullable=True)
    cps_twenty_years_ago = Column(Numeric, nullable=True)
    cps_thirty_years_ago = Column(Numeric, nullable=True)
    cps_fourty_years_ago = Column(Numeric, nullable=True)
    cps_fifty_years_ago = Column(Numeric, nullable=True)
    cps_low = Column(Numeric, nullable=True)
    cps_low_current_year = Column(Numeric, nullable=True)
    cps_low_two_years = Column(Numeric, nullable=True)
    cps_low_five_years = Column(Numeric, nullable=True)
    cps_low_ten_years = Column(Numeric, nullable=True)
    cps_low_twenty_years = Column(Numeric, nullable=True)
    cps_high = Column(Numeric, nullable=True)
    cps_high_current_year = Column(Numeric, nullable=True)
    cps_high_two_years = Column(Numeric, nullable=True)
    cps_high_five_years = Column(Numeric, nullable=True)
    cps_high_ten_years = Column(Numeric, nullable=True)
    cps_high_twenty_years = Column(Numeric, nullable=True)
    cps_mean = Column(Numeric, nullable=True)
    cps_mean_current_year = Column(Numeric, nullable=True)
    cps_mean_two_years = Column(Numeric, nullable=True)
    cps_mean_five_years = Column(Numeric, nullable=True)
    cps_mean_ten_years = Column(Numeric, nullable=True)
    cps_mean_twenty_years = Column(Numeric, nullable=True)
    cps_std_dev = Column(Numeric, nullable=True)
    cps_std_dev_current_year = Column(Numeric, nullable=True)
    cps_std_dev_two_years = Column(Numeric, nullable=True)
    cps_std_dev_five_years = Column(Numeric, nullable=True)
    cps_std_dev_ten_years = Column(Numeric, nullable=True)
    cps_std_dev_twenty_years = Column(Numeric, nullable=True)

    capexps__current = Column(Numeric, nullable=True)
    capexps_one_quarter_ago = Column(Numeric, nullable=True)
    capexps_two_quarters_ago = Column(Numeric, nullable=True)
    capexps_three_quarters_ago = Column(Numeric, nullable=True)
    capexps_one_year_ago = Column(Numeric, nullable=True)
    capexps_one_year_half_ago = Column(Numeric, nullable=True)
    capexps_two_years_ago_ago = Column(Numeric, nullable=True)
    capexps_three_years_ago = Column(Numeric, nullable=True)
    capexps_four_years_ago = Column(Numeric, nullable=True)
    capexps_five_years_ago = Column(Numeric, nullable=True)
    capexps_ten_years_ago = Column(Numeric, nullable=True)
    capexps_fifteen_years_ago = Column(Numeric, nullable=True)
    capexps_twenty_years_ago = Column(Numeric, nullable=True)
    capexps_thirty_years_ago = Column(Numeric, nullable=True)
    capexps_fourty_years_ago = Column(Numeric, nullable=True)
    capexps_fifty_years_ago = Column(Numeric, nullable=True)
    capexps_low = Column(Numeric, nullable=True)
    capexps_low_current_year = Column(Numeric, nullable=True)
    capexps_low_two_years = Column(Numeric, nullable=True)
    capexps_low_five_years = Column(Numeric, nullable=True)
    capexps_low_ten_years = Column(Numeric, nullable=True)
    capexps_low_twenty_years = Column(Numeric, nullable=True)
    capexps_high = Column(Numeric, nullable=True)
    capexps_high_current_year = Column(Numeric, nullable=True)
    capexps_high_two_years = Column(Numeric, nullable=True)
    capexps_high_five_years = Column(Numeric, nullable=True)
    capexps_high_ten_years = Column(Numeric, nullable=True)
    capexps_high_twenty_years = Column(Numeric, nullable=True)
    capexps_mean = Column(Numeric, nullable=True)
    capexps_mean_current_year = Column(Numeric, nullable=True)
    capexps_mean_two_years = Column(Numeric, nullable=True)
    capexps_mean_five_years = Column(Numeric, nullable=True)
    capexps_mean_ten_years = Column(Numeric, nullable=True)
    capexps_mean_twenty_years = Column(Numeric, nullable=True)
    capexps_std_dev = Column(Numeric, nullable=True)
    capexps_std_dev_current_year = Column(Numeric, nullable=True)
    capexps_std_dev_two_years = Column(Numeric, nullable=True)
    capexps_std_dev_five_years = Column(Numeric, nullable=True)
    capexps_std_dev_ten_years = Column(Numeric, nullable=True)
    capexps_std_dev_twenty_years = Column(Numeric, nullable=True)
    
    #dividends paid to shareholders / number of shares outstanding
    dps_current = Column(Numeric, nullable=True)
    dps_one_quarter_ago = Column(Numeric, nullable=True)
    dps_two_quarters_ago = Column(Numeric, nullable=True)
    dps_three_quarters_ago = Column(Numeric, nullable=True)
    dps_one_year_ago = Column(Numeric, nullable=True)
    dps_one_year_half_ago = Column(Numeric, nullable=True)
    dps_two_years_ago_ago = Column(Numeric, nullable=True)
    dps_three_years_ago = Column(Numeric, nullable=True)
    dps_four_years_ago = Column(Numeric, nullable=True)
    dps_five_years_ago = Column(Numeric, nullable=True)
    dps_ten_years_ago = Column(Numeric, nullable=True)
    dps_fifteen_years_ago = Column(Numeric, nullable=True)
    dps_twenty_years_ago = Column(Numeric, nullable=True)
    dps_thirty_years_ago = Column(Numeric, nullable=True)
    dps_fourty_years_ago = Column(Numeric, nullable=True)
    dps_fifty_years_ago = Column(Numeric, nullable=True)
    dps_low = Column(Numeric, nullable=True)
    dps_low_current_year = Column(Numeric, nullable=True)
    dps_low_two_years = Column(Numeric, nullable=True)
    dps_low_five_years = Column(Numeric, nullable=True)
    dps_low_ten_years = Column(Numeric, nullable=True)
    dps_low_twenty_years = Column(Numeric, nullable=True)
    dps_high = Column(Numeric, nullable=True)
    dps_high_current_year = Column(Numeric, nullable=True)
    dps_high_two_years = Column(Numeric, nullable=True)
    dps_high_five_years = Column(Numeric, nullable=True)
    dps_high_ten_years = Column(Numeric, nullable=True)
    dps_high_twenty_years = Column(Numeric, nullable=True)
    dps_mean = Column(Numeric, nullable=True)
    dps_mean_current_year = Column(Numeric, nullable=True)
    dps_mean_two_years = Column(Numeric, nullable=True)
    dps_mean_five_years = Column(Numeric, nullable=True)
    dps_mean_ten_years = Column(Numeric, nullable=True)
    dps_mean_twenty_years = Column(Numeric, nullable=True)
    dps_std_dev = Column(Numeric, nullable=True)
    dps_std_dev_current_year = Column(Numeric, nullable=True)
    dps_std_dev_two_years = Column(Numeric, nullable=True)
    dps_std_dev_five_years = Column(Numeric, nullable=True)
    dps_std_dev_ten_years = Column(Numeric, nullable=True)
    dps_std_dev_twenty_years = Column(Numeric, nullable=True)
    
    #dividends paid / net income 
    dividend_payout_ratio_current = Column(Numeric, nullable=True)
    dividend_payout_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_one_year_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_three_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_four_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_five_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_ten_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    dividend_payout_ratio_low = Column(Numeric, nullable=True)
    dividend_payout_ratio_low_current_year = Column(Numeric, nullable=True)
    dividend_payout_ratio_low_two_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_low_five_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_low_ten_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_low_twenty_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_high = Column(Numeric, nullable=True)
    dividend_payout_ratio_high_current_year = Column(Numeric, nullable=True)
    dividend_payout_ratio_high_two_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_high_five_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_high_ten_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_high_twenty_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_mean = Column(Numeric, nullable=True)
    dividend_payout_ratio_mean_current_year = Column(Numeric, nullable=True)
    dividend_payout_ratio_mean_two_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_mean_five_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_mean_ten_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_std_dev = Column(Numeric, nullable=True)
    dividend_payout_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    dividend_payout_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    dividend_payout_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)
    
    #stock price / book value per share = stock price / ((total equity - preferred equity) / total shares outstanding)
    pb_ratio_current = Column(Numeric, nullable=True)
    pb_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    pb_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    pb_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    pb_ratio_one_year_ago = Column(Numeric, nullable=True)
    pb_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    pb_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    pb_ratio_three_years_ago = Column(Numeric, nullable=True)
    pb_ratio_four_years_ago = Column(Numeric, nullable=True)
    pb_ratio_five_years_ago = Column(Numeric, nullable=True)
    pb_ratio_ten_years_ago = Column(Numeric, nullable=True)
    pb_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    pb_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    pb_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    pb_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    pb_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    pb_ratio_low = Column(Numeric, nullable=True)
    pb_ratio_low_current_year = Column(Numeric, nullable=True)
    pb_ratio_low_two_years = Column(Numeric, nullable=True)
    pb_ratio_low_five_years = Column(Numeric, nullable=True)
    pb_ratio_low_ten_years = Column(Numeric, nullable=True)
    pb_ratio_low_twenty_years = Column(Numeric, nullable=True)
    pb_ratio_high = Column(Numeric, nullable=True)
    pb_ratio_high_current_year = Column(Numeric, nullable=True)
    pb_ratio_high_two_years = Column(Numeric, nullable=True)
    pb_ratio_high_five_years = Column(Numeric, nullable=True)
    pb_ratio_high_ten_years = Column(Numeric, nullable=True)
    pb_ratio_high_twenty_years = Column(Numeric, nullable=True)
    pb_ratio_mean = Column(Numeric, nullable=True)
    pb_ratio_mean_current_year = Column(Numeric, nullable=True)
    pb_ratio_mean_two_years = Column(Numeric, nullable=True)
    pb_ratio_mean_five_years = Column(Numeric, nullable=True)
    pb_ratio_mean_ten_years = Column(Numeric, nullable=True)
    pb_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    pb_ratio_std_dev = Column(Numeric, nullable=True)
    pb_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    pb_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    pb_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    pb_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    pb_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #stock price / eps
    pe_ratio_current = Column(Numeric, nullable=True)
    pe_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    pe_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    pe_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    pe_ratio_one_year_ago = Column(Numeric, nullable=True)
    pe_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    pe_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    pe_ratio_three_years_ago = Column(Numeric, nullable=True)
    pe_ratio_four_years_ago = Column(Numeric, nullable=True)
    pe_ratio_five_years_ago = Column(Numeric, nullable=True)
    pe_ratio_ten_years_ago = Column(Numeric, nullable=True)
    pe_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    pe_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    pe_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    pe_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    pe_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    pe_ratio_low = Column(Numeric, nullable=True)
    pe_ratio_low_current_year = Column(Numeric, nullable=True)
    pe_ratio_low_two_years = Column(Numeric, nullable=True)
    pe_ratio_low_five_years = Column(Numeric, nullable=True)
    pe_ratio_low_ten_years = Column(Numeric, nullable=True)
    pe_ratio_low_twenty_years = Column(Numeric, nullable=True)
    pe_ratio_high = Column(Numeric, nullable=True)
    pe_ratio_high_current_year = Column(Numeric, nullable=True)
    pe_ratio_high_two_years = Column(Numeric, nullable=True)
    pe_ratio_high_five_years = Column(Numeric, nullable=True)
    pe_ratio_high_ten_years = Column(Numeric, nullable=True)
    pe_ratio_high_twenty_years = Column(Numeric, nullable=True)
    pe_ratio_mean = Column(Numeric, nullable=True)
    pe_ratio_mean_current_year = Column(Numeric, nullable=True)
    pe_ratio_mean_two_years = Column(Numeric, nullable=True)
    pe_ratio_mean_five_years = Column(Numeric, nullable=True)
    pe_ratio_mean_ten_years = Column(Numeric, nullable=True)
    pe_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    pe_ratio_std_dev = Column(Numeric, nullable=True)
    pe_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    pe_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    pe_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    pe_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    pe_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)
    
    #stock price / revenue per share
    ps_ratio_current = Column(Numeric, nullable=True)
    ps_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    ps_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    ps_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    ps_ratio_one_year_ago = Column(Numeric, nullable=True)
    ps_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    ps_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    ps_ratio_three_years_ago = Column(Numeric, nullable=True)
    ps_ratio_four_years_ago = Column(Numeric, nullable=True)
    ps_ratio_five_years_ago = Column(Numeric, nullable=True)
    ps_ratio_ten_years_ago = Column(Numeric, nullable=True)
    ps_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    ps_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    ps_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    ps_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    ps_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    ps_ratio_low = Column(Numeric, nullable=True)
    ps_ratio_low_current_year = Column(Numeric, nullable=True)
    ps_ratio_low_two_years = Column(Numeric, nullable=True)
    ps_ratio_low_five_years = Column(Numeric, nullable=True)
    ps_ratio_low_ten_years = Column(Numeric, nullable=True)
    ps_ratio_low_twenty_years = Column(Numeric, nullable=True)
    ps_ratio_high = Column(Numeric, nullable=True)
    ps_ratio_high_current_year = Column(Numeric, nullable=True)
    ps_ratio_high_two_years = Column(Numeric, nullable=True)
    ps_ratio_high_five_years = Column(Numeric, nullable=True)
    ps_ratio_high_ten_years = Column(Numeric, nullable=True)
    ps_ratio_high_twenty_years = Column(Numeric, nullable=True)
    ps_ratio_mean = Column(Numeric, nullable=True)
    ps_ratio_mean_current_year = Column(Numeric, nullable=True)
    ps_ratio_mean_two_years = Column(Numeric, nullable=True)
    ps_ratio_mean_five_years = Column(Numeric, nullable=True)
    ps_ratio_mean_ten_years = Column(Numeric, nullable=True)
    ps_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    ps_ratio_std_dev = Column(Numeric, nullable=True)
    ps_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    ps_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    ps_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    ps_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    ps_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    #pe ratio / eps growth
    peg_ratio_current = Column(Numeric, nullable=True)
    peg_ratio_one_quarter_ago = Column(Numeric, nullable=True)
    peg_ratio_two_quarters_ago = Column(Numeric, nullable=True)
    peg_ratio_three_quarters_ago = Column(Numeric, nullable=True)
    peg_ratio_one_year_ago = Column(Numeric, nullable=True)
    peg_ratio_one_year_half_ago = Column(Numeric, nullable=True)
    peg_ratio_two_years_ago_ago = Column(Numeric, nullable=True)
    peg_ratio_three_years_ago = Column(Numeric, nullable=True)
    peg_ratio_four_years_ago = Column(Numeric, nullable=True)
    peg_ratio_five_years_ago = Column(Numeric, nullable=True)
    peg_ratio_ten_years_ago = Column(Numeric, nullable=True)
    peg_ratio_fifteen_years_ago = Column(Numeric, nullable=True)
    peg_ratio_twenty_years_ago = Column(Numeric, nullable=True)
    peg_ratio_thirty_years_ago = Column(Numeric, nullable=True)
    peg_ratio_fourty_years_ago = Column(Numeric, nullable=True)
    peg_ratio_fifty_years_ago = Column(Numeric, nullable=True)
    peg_ratio_low = Column(Numeric, nullable=True)
    peg_ratio_low_current_year = Column(Numeric, nullable=True)
    peg_ratio_low_two_years = Column(Numeric, nullable=True)
    peg_ratio_low_five_years = Column(Numeric, nullable=True)
    peg_ratio_low_ten_years = Column(Numeric, nullable=True)
    peg_ratio_low_twenty_years = Column(Numeric, nullable=True)
    peg_ratio_high = Column(Numeric, nullable=True)
    peg_ratio_high_current_year = Column(Numeric, nullable=True)
    peg_ratio_high_two_years = Column(Numeric, nullable=True)
    peg_ratio_high_five_years = Column(Numeric, nullable=True)
    peg_ratio_high_ten_years = Column(Numeric, nullable=True)
    peg_ratio_high_twenty_years = Column(Numeric, nullable=True)
    peg_ratio_mean = Column(Numeric, nullable=True)
    peg_ratio_mean_current_year = Column(Numeric, nullable=True)
    peg_ratio_mean_two_years = Column(Numeric, nullable=True)
    peg_ratio_mean_five_years = Column(Numeric, nullable=True)
    peg_ratio_mean_ten_years = Column(Numeric, nullable=True)
    peg_ratio_mean_twenty_years = Column(Numeric, nullable=True)
    peg_ratio_std_dev = Column(Numeric, nullable=True)
    peg_ratio_std_dev_current_year = Column(Numeric, nullable=True)
    peg_ratio_std_dev_two_years = Column(Numeric, nullable=True)
    peg_ratio_std_dev_five_years = Column(Numeric, nullable=True)
    peg_ratio_std_dev_ten_years = Column(Numeric, nullable=True)
    peg_ratio_std_dev_twenty_years = Column(Numeric, nullable=True)

    update_stamp = Column(DateTime(timezone=True), nullable=True, server_default=FetchedValue())